- type: latheRecipePack
  id: IntegratedWeaponAugments
  recipes:
  - AugmentStunnerPanel
  - AugmentStunbatonPanel

- type: latheRecipePack
  id: IntegratedAdvancedWeaponAugments
  recipes:
  - AugmentLaserPistolPanel
  - AugmentSubdermalArmorCasing
