// SPDX-FileCopyrightText: 2025 Aiden <28298836+Aidenkrz@users.noreply.github.com>
// SPDX-FileCopyrightText: 2025 ArtisticRoomba <145879011+ArtisticRoomba@users.noreply.github.com>
// SPDX-FileCopyrightText: 2025 GoobBot <uristmchands@proton.me>
// SPDX-FileCopyrightText: 2025 SX-7 <sn1.test.preria.2002@gmail.com>
// SPDX-FileCopyrightText: 2025 chromiumboy <50505512+chromiumboy@users.noreply.github.com>
// SPDX-FileCopyrightText: 2025 pathetic meowmeow <uhhadd@gmail.com>
//
// SPDX-License-Identifier: AGPL-3.0-or-later

using Content.Client.Pinpointer.UI;
using Content.Client._Onyx.ZLevels.UI;
using Content.Client.UserInterface.Controls;
using Content.Shared.Atmos.Components;
using Content.Shared.Prototypes;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Map;
using Robust.Shared.Prototypes;
using Robust.Shared.Timing;
using Robust.Shared.Utility;
using System.Diagnostics.CodeAnalysis;
using System.Linq;
using System.Numerics;

namespace Content.Client.Atmos.Consoles;

[GenerateTypedNameReferences]
public sealed partial class AtmosMonitoringConsoleWindow : FancyWindow
{
    private readonly IEntityManager _entManager;
    private readonly IPrototypeManager _protoManager;
    private readonly SpriteSystem _spriteSystem;

    private EntityUid? _owner;
    private NetEntity? _focusEntity;
    private int? _focusNetId;
    // <Onyx-Tweak>
    private readonly List<int> _knownFloors = new();
    private int? _selectedFloorDepth;
    private bool _updatingFloorSelector;
    private bool _hasCachedState;
    private bool _showMonitorBlip = true;
    private EntityCoordinates? _cachedConsoleCoords;
    private AtmosMonitoringConsoleEntry[] _cachedAtmosNetworks = Array.Empty<AtmosMonitoringConsoleEntry>();
    private Dictionary<NetEntity, AtmosDeviceNavMapData> _visibleAtmosDevices = new();
    // </Onyx-Tweak>

    private bool _autoScrollActive = false;

    private readonly Color _unfocusedDeviceColor = Color.DimGray;
    private ProtoId<NavMapBlipPrototype> _navMapConsoleProtoId = "NavMapConsole";
    private ProtoId<NavMapBlipPrototype> _gasPipeSensorProtoId = "GasPipeSensor";

    private readonly Vector2[] _pipeLayerOffsets = { new Vector2(0f, 0f), new Vector2(0.25f, 0.25f), new Vector2(-0.25f, -0.25f) };
    public event Action<int>? FloorSelected; // <Onyx-Tweak>

    public AtmosMonitoringConsoleWindow(AtmosMonitoringConsoleBoundUserInterface userInterface, EntityUid? owner)
    {
        RobustXamlLoader.Load(this);
        _entManager = IoCManager.Resolve<IEntityManager>();
        _protoManager = IoCManager.Resolve<IPrototypeManager>();
        _spriteSystem = _entManager.System<SpriteSystem>();

        // Pass the owner to nav map
        _owner = owner;
        NavMap.Owner = _owner;

        // Set nav map grid uid
        var stationName = Loc.GetString("atmos-monitoring-window-unknown-location");
        EntityCoordinates? consoleCoords = null;

        if (_entManager.TryGetComponent<TransformComponent>(owner, out var xform))
        {
            consoleCoords = xform.Coordinates;
            NavMap.MapUid = xform.GridUid;

            // Assign station name
            if (_entManager.TryGetComponent<MetaDataComponent>(xform.GridUid, out var stationMetaData))
                stationName = stationMetaData.EntityName;

            var msg = new FormattedMessage();
            msg.TryAddMarkup(Loc.GetString("atmos-monitoring-window-station-name", ("stationName", stationName)), out _);

            StationName.SetMessage(msg);
        }

        else
        {
            StationName.SetMessage(stationName);
            NavMap.Visible = false;
        }

        // Set trackable entity selected action
        NavMap.TrackedEntitySelectedAction += SetTrackedEntityFromNavMap;

        // Update nav map
        NavMap.ForceNavMapUpdate();

        // Set tab container headers
        MasterTabContainer.SetTabTitle(0, Loc.GetString("atmos-monitoring-window-tab-networks"));

        // Set UI toggles
        ShowPipeNetwork.OnToggled += _ => OnShowPipeNetworkToggled();
        ShowGasPipeSensors.OnToggled += _ => OnShowGasPipeSensors();
        FloorSelector.OnItemSelected += OnFloorSelected; // <Onyx-Tweak>

        // Set nav map colors
        if (!_entManager.TryGetComponent<AtmosMonitoringConsoleComponent>(_owner, out var console))
            return;

        NavMap.TileColor = console.NavMapTileColor;
        NavMap.WallColor = console.NavMapWallColor;

        // Initalize
        UpdateUI(consoleCoords, Array.Empty<AtmosMonitoringConsoleEntry>());
    }

    #region Toggle handling

    private void OnShowPipeNetworkToggled()
    {
        NavMap.ShowPipeNetwork = ShowPipeNetwork.Pressed;
        RefreshNavMapEntities(); // <Onyx-Tweak edited>
    }

    private void OnShowGasPipeSensors()
    {
        RefreshNavMapEntities(); // <Onyx-Tweak edited>
    }

    #endregion

    public void UpdateUI
        (EntityCoordinates? consoleCoords,
        AtmosMonitoringConsoleEntry[] atmosNetworks)
    {
        if (_owner == null)
            return;

        if (!_entManager.TryGetComponent<AtmosMonitoringConsoleComponent>(_owner.Value, out var console))
            return;

        // <Onyx-Tweak>
        _cachedConsoleCoords = consoleCoords;
        _cachedAtmosNetworks = atmosNetworks;
        _hasCachedState = true;

        var floorState = ZLevelFloorSelectorHelper.GetFloorState(_entManager, _owner.Value, _selectedFloorDepth);
        _selectedFloorDepth = floorState.SelectedFloor;
        UpdateFloors(floorState.Floors, floorState.SelectedFloor, floorState.MonitorFloor);

        var selectedFloor = floorState.SelectedFloor;
        var hasFloorFilter = floorState.HasFloorSelection;
        var selectedNavMap = ZLevelFloorSelectorHelper.ResolveNavMapUidForMap(_entManager, floorState.SelectedMap);
        NavMap.MapUid = selectedNavMap;
        NavMap.Visible = selectedNavMap != null;

        _visibleAtmosDevices = hasFloorFilter
            ? FilterDevicesByFloor(console.AtmosDevices, selectedFloor, floorState.SelectedMap)
            : new Dictionary<NetEntity, AtmosDeviceNavMapData>(console.AtmosDevices);

        if (hasFloorFilter)
            atmosNetworks = FilterEntriesByFloor(atmosNetworks, selectedFloor, floorState.SelectedMap);

        _showMonitorBlip = consoleCoords != null && (!hasFloorFilter || selectedFloor == floorState.MonitorFloor);
        // </Onyx-Tweak>

        // Reset nav map values
        NavMap.TrackedCoordinates.Clear();
        if (_focusEntity != null && !_visibleAtmosDevices.ContainsKey(_focusEntity.Value)) // <Onyx-Tweak edited>
            ClearFocus();

        RefreshNavMapEntities(); // <Onyx-Tweak edited>

        // Clear excess children from the tables
        while (AtmosNetworksTable.ChildCount > atmosNetworks.Length)
            AtmosNetworksTable.RemoveChild(AtmosNetworksTable.GetChild(AtmosNetworksTable.ChildCount - 1));

        // Update all entries in each table
        for (int index = 0; index < atmosNetworks.Length; index++)
        {
            var entry = atmosNetworks.ElementAt(index);
            UpdateUIEntry(entry, index, AtmosNetworksTable); // <Onyx-Tweak edited>
        }
    }

    private void UpdateNavMapBlips()
    {
        if (NavMap.Visible)
        {
            foreach (var (netEnt, device) in _visibleAtmosDevices) // <Onyx-Tweak edited>
            {
                // Update the focus network ID, incase it has changed
                if (_focusEntity == netEnt)
                {
                    _focusNetId = device.NetId;
                    NavMap.FocusNetId = _focusNetId;
                }

                var isSensor = device.NavMapBlip == _gasPipeSensorProtoId;

                // Skip network devices if the toggled is off
                if (!ShowPipeNetwork.Pressed && !isSensor)
                    continue;

                // Skip gas pipe sensors if the toggle is off
                if (!ShowGasPipeSensors.Pressed && isSensor)
                    continue;

                AddTrackedEntityToNavMap(device, isSensor);
            }
        }
    }

    // <Onyx-Tweak>
    private void RefreshNavMapEntities()
    {
        NavMap.TrackedEntities.Clear();
        UpdateNavMapBlips();

        var consoleNetEnt = _entManager.GetNetEntity(_owner);

        if (_showMonitorBlip && _cachedConsoleCoords != null && consoleNetEnt != null)
        {
            var proto = _protoManager.Index(_navMapConsoleProtoId);

            if (proto.TexturePaths != null && proto.TexturePaths.Length != 0)
            {
                var texture = _spriteSystem.Frame0(new SpriteSpecifier.Texture(proto.TexturePaths[0]));
                var blip = new NavMapBlip(_cachedConsoleCoords.Value, texture, proto.Color, proto.Blinks, proto.Selectable);
                NavMap.TrackedEntities[consoleNetEnt.Value] = blip;
            }
        }

        NavMap.ForceNavMapUpdate();
    }
    // </Onyx-Tweak>

    private void AddTrackedEntityToNavMap(AtmosDeviceNavMapData metaData, bool isSensor = false)
    {
        var proto = _protoManager.Index(metaData.NavMapBlip);

        if (proto.TexturePaths == null || proto.TexturePaths.Length == 0)
            return;

        var idx = Math.Clamp((int)metaData.Direction / 2, 0, proto.TexturePaths.Length - 1);
        var texture = proto.TexturePaths.Length > 0 ? proto.TexturePaths[idx] : proto.TexturePaths[0];
        var color = isSensor ? proto.Color : proto.Color * metaData.PipeColor;

        if (_focusNetId != null && metaData.NetId != _focusNetId)
            color *= _unfocusedDeviceColor;

        var blinks = proto.Blinks || _focusEntity == metaData.NetEntity;
        var coords = _entManager.GetCoordinates(metaData.NetCoordinates);

        if (proto.Placement == NavMapBlipPlacement.Offset && metaData.PipeLayer > 0)
            coords = coords.Offset(_pipeLayerOffsets[(int)metaData.PipeLayer]);

        var blip = new NavMapBlip(coords, _spriteSystem.Frame0(new SpriteSpecifier.Texture(texture)), color, blinks, proto.Selectable, proto.Scale);
        NavMap.TrackedEntities[metaData.NetEntity] = blip;
    }

    private void UpdateUIEntry(AtmosMonitoringConsoleEntry data, int index, Control table) // <Onyx-Tweak edited>
    {
        // Make new UI entry if required
        if (index >= table.ChildCount)
        {
            var newEntryContainer = new AtmosMonitoringEntryContainer(data);

            // On click
            newEntryContainer.FocusButton.OnButtonUp += args =>
            {
                if (_focusEntity == newEntryContainer.Data.NetEntity)
                {
                    ClearFocus();
                }

                else
                {
                    SetFocus(newEntryContainer.Data.NetEntity, newEntryContainer.Data.NetId);

                    var coords = _entManager.GetCoordinates(newEntryContainer.Data.Coordinates);
                    NavMap.CenterToCoordinates(coords);
                }

                // Update affected UI elements across all tables
                UpdateConsoleTable(AtmosNetworksTable, _focusEntity); // <Onyx-Tweak edited>
            };

            // Add the entry to the current table
            table.AddChild(newEntryContainer);
        }

        // Update values and UI elements
        var tableChild = table.GetChild(index);

        if (tableChild is not AtmosMonitoringEntryContainer)
        {
            table.RemoveChild(tableChild);
            UpdateUIEntry(data, index, table); // <Onyx-Tweak edited>

            return;
        }

        var entryContainer = (AtmosMonitoringEntryContainer)tableChild;
        entryContainer.UpdateEntry(data, data.NetEntity == _focusEntity);
    }

    private void UpdateConsoleTable(Control table, NetEntity? currTrackedEntity) // <Onyx-Tweak edited>
    {
        foreach (var tableChild in table.Children)
        {
            if (tableChild is not AtmosMonitoringEntryContainer) // <Onyx-Tweak edited>
                continue;

            var entryContainer = (AtmosMonitoringEntryContainer)tableChild; // <Onyx-Tweak edited>

            if (entryContainer.Data.NetEntity != currTrackedEntity) // <Onyx-Tweak edited>
                entryContainer.RemoveAsFocus();

            else if (entryContainer.Data.NetEntity == currTrackedEntity) // <Onyx-Tweak edited>
                entryContainer.SetAsFocus();
        }
    }

    private void SetTrackedEntityFromNavMap(NetEntity? focusEntity)
    {
        if (focusEntity == null)
            return;

        if (!_entManager.TryGetComponent<AtmosMonitoringConsoleComponent>(_owner, out var console))
            return;

        foreach (var (netEnt, device) in console.AtmosDevices)
        {
            if (netEnt != focusEntity)
                continue;

            if (device.NavMapBlip != _gasPipeSensorProtoId)
                return;

            // Set new focus
            SetFocus(focusEntity.Value, device.NetId);

            // Get the scroll position of the selected entity on the selected button the UI
            ActivateAutoScrollToFocus();

            break;
        }
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        AutoScrollToFocus();
    }

    // <Onyx-Tweak>
    private void OnFloorSelected(OptionButton.ItemSelectedEventArgs args)
    {
        args.Button.SelectId(args.Id);

        if (_updatingFloorSelector || args.Id < 0 || args.Id >= _knownFloors.Count)
            return;

        _selectedFloorDepth = _knownFloors[args.Id];
        ClearFocus();
        FloorSelected?.Invoke(_selectedFloorDepth.Value);
    }

    private void UpdateFloors(List<int> floors, int selectedFloor, int monitorFloor)
    {
        _knownFloors.Clear();
        _knownFloors.AddRange(floors);

        _updatingFloorSelector = true;
        FloorSelector.Clear();

        for (var i = 0; i < floors.Count; i++)
        {
            FloorSelector.AddItem(ZLevelFloorSelectorHelper.FormatRelativeFloor(floors[i], monitorFloor), i);
        }

        var selectedId = 0;
        for (var i = 0; i < floors.Count; i++)
        {
            if (floors[i] != selectedFloor)
                continue;

            selectedId = i;
            break;
        }

        FloorSelector.SelectId(selectedId);
        _updatingFloorSelector = false;
        FloorSelectorContainer.Visible = floors.Count > 1;
    }

    private Dictionary<NetEntity, AtmosDeviceNavMapData> FilterDevicesByFloor(
        IReadOnlyDictionary<NetEntity, AtmosDeviceNavMapData> source,
        int selectedFloor,
        EntityUid? selectedMap)
    {
        var filtered = new Dictionary<NetEntity, AtmosDeviceNavMapData>();
        foreach (var (netEntity, data) in source)
        {
            if (!BelongsToSelectedFloor(data.NetCoordinates, selectedFloor, selectedMap))
                continue;

            filtered[netEntity] = data;
        }

        return filtered;
    }

    private AtmosMonitoringConsoleEntry[] FilterEntriesByFloor(
        AtmosMonitoringConsoleEntry[] source,
        int selectedFloor,
        EntityUid? selectedMap)
    {
        if (source.Length == 0)
            return source;

        var filtered = new List<AtmosMonitoringConsoleEntry>(source.Length);
        foreach (var entry in source)
        {
            if (!BelongsToSelectedFloor(entry.Coordinates, selectedFloor, selectedMap))
                continue;

            filtered.Add(entry);
        }

        return filtered.ToArray();
    }

    private bool BelongsToSelectedFloor(NetCoordinates coords, int selectedFloor, EntityUid? selectedMap)
    {
        if (selectedMap != null &&
            ZLevelFloorSelectorHelper.TryGetCoordinatesMapUid(_entManager, coords, out var mapUid))
        {
            return mapUid == selectedMap.Value;
        }

        if (TryGetDepth(coords, out var depth))
            return depth == selectedFloor;

        // Do not leak unknown entries into selected floors.
        return false;
    }

    private bool TryGetDepth(NetCoordinates coords, out int depth)
    {
        var entityCoordinates = _entManager.GetCoordinates(coords);
        return ZLevelFloorSelectorHelper.TryGetEntityDepth(_entManager, entityCoordinates.EntityId, out depth);
    }
    // </Onyx-Tweak>

    private void ActivateAutoScrollToFocus()
    {
        _autoScrollActive = true;
    }

    private void AutoScrollToFocus()
    {
        if (!_autoScrollActive)
            return;

        var scroll = AtmosNetworksTable.Parent as ScrollContainer;
        if (scroll == null)
            return;

        if (!TryGetNextScrollPosition(out float? nextScrollPosition))
            return;

        scroll.VScrollTarget = nextScrollPosition.Value;

        if (MathHelper.CloseToPercent(scroll.VScroll, scroll.VScrollTarget))
            _autoScrollActive = false;
    }

    private bool TryGetNextScrollPosition([NotNullWhen(true)] out float? nextScrollPosition)
    {
        nextScrollPosition = null;

        var scroll = AtmosNetworksTable.Parent as ScrollContainer;
        if (scroll == null)
            return false;

        var container = scroll.Children.ElementAt(0) as BoxContainer;
        if (container == null || container.Children.Count() == 0)
            return false;

        // Exit if the heights of the children haven't been initialized yet
        if (!container.Children.Any(x => x.Height > 0))
            return false;

        nextScrollPosition = 0;

        foreach (var control in container.Children)
        {
            if (control is not AtmosMonitoringEntryContainer)
                continue;

            var entry = (AtmosMonitoringEntryContainer)control;

            if (entry.Data.NetEntity == _focusEntity)
                return true;

            nextScrollPosition += control.Height;
        }

        // Failed to find control
        nextScrollPosition = null;

        return false;
    }

    private void SetFocus(NetEntity focusEntity, int focusNetId)
    {
        _focusEntity = focusEntity;
        _focusNetId = focusNetId;
        NavMap.FocusNetId = focusNetId;

        OnFocusChanged();
    }

    private void ClearFocus()
    {
        _focusEntity = null;
        _focusNetId = null;
        NavMap.FocusNetId = null;

        OnFocusChanged();
    }

    private void OnFocusChanged()
    {
        RefreshNavMapEntities(); // <Onyx-Tweak edited>

        for (int index = 0; index < AtmosNetworksTable.ChildCount; index++)
        {
            var entry = (AtmosMonitoringEntryContainer)AtmosNetworksTable.GetChild(index);

            if (entry == null)
                continue;

            UpdateUIEntry(entry.Data, index, AtmosNetworksTable); // <Onyx-Tweak edited>
        }
    }
}