using Content.Shared._Onyx.Telecommunications;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;
using System.Linq;
using System.Numerics;

namespace Content.Client._Onyx.Telecommunications;

[GenerateTypedNameReferences]
public sealed partial class TelecomTrafficConsoleWindow : DefaultWindow
{
    private enum LogOutcomeFilter : byte
    {
        All,
        Successful,
        Failed,
    }

    public event Action<NetEntity>? OnServerSelected;
    public event Action<bool>? OnRoutingToggled;
    public event Action<string>? OnChannelToggled;

    private TelecomTrafficConsoleState? _state;
    private readonly List<string> _channels = [];
    private string? _selectedChannel;
    private LogOutcomeFilter _logOutcomeFilter;
    private bool _routingEnabled;

    public TimeSpan CurrentTime;

    public TelecomTrafficConsoleWindow()
    {
        RobustXamlLoader.Load(this);

        ServerList.OnItemSelected += OnServerListSelected;
        RoutingButton.OnPressed += _ => OnRoutingToggled?.Invoke(!_routingEnabled);

        GraphChannelFilter.OnItemSelected += args =>
        {
            GraphChannelFilter.SelectId(args.Id);
            _selectedChannel = args.Id == 0 ? null : _channels[args.Id - 1];
            RefreshGraph();
        };

        LogStatusFilter.AddItem(Loc.GetString("telecom-traffic-console-log-filter-all"), (int) LogOutcomeFilter.All);
        LogStatusFilter.AddItem(Loc.GetString("telecom-traffic-console-log-filter-successful"), (int) LogOutcomeFilter.Successful);
        LogStatusFilter.AddItem(Loc.GetString("telecom-traffic-console-log-filter-failed"), (int) LogOutcomeFilter.Failed);
        LogStatusFilter.SelectId((int) LogOutcomeFilter.All);
        LogStatusFilter.OnItemSelected += args =>
        {
            LogStatusFilter.SelectId(args.Id);
            _logOutcomeFilter = (LogOutcomeFilter) args.Id;
            RefreshLog();
        };

        SuccessfulFilter.OnToggled += _ => RefreshGraph();
        FailedFilter.OnToggled += _ => RefreshGraph();
        LiveLogButton.OnToggled += _ =>
        {
            if (LiveLogButton.Pressed)
                LogScroll.SetScrollValue(Vector2.Zero);
        };
        LogSearch.OnTextChanged += _ => RefreshLog();
    }

    public void UpdateState(TelecomTrafficConsoleState state)
    {
        _state = state;

        ServerList.OnItemSelected -= OnServerListSelected;
        ServerList.Clear();

        foreach (var server in state.Servers)
        {
            var item = ServerList.AddItem($"{server.Name}");
            item.Metadata = server.Entity;
            item.Selected = state.SelectedServer == server.Entity;
        }

        ServerList.OnItemSelected += OnServerListSelected;

        ServerCountLabel.Text = Loc.GetString(
            "telecom-traffic-console-servers",
            ("count", state.Servers.Count));

        _routingEnabled = state.RoutingEnabled;
        RoutingButton.Text = Loc.GetString(
            _routingEnabled
                ? "telecom-traffic-console-disable-routing"
                : "telecom-traffic-console-enable-routing");
        RoutingButton.Disabled = state.SelectedServer == null;

        RoutingStatusLabel.Text = Loc.GetString(
            _routingEnabled
                ? "telecom-traffic-console-routing-online"
                : "telecom-traffic-console-routing-offline");
        RoutingStatusLabel.FontColorOverride = _routingEnabled
            ? Color.FromHex("#45e67b")
            : Color.FromHex("#e65454");
        DiagnosticStatusLabel.Text = Loc.GetString(
            "telecom-traffic-console-diagnostics",
            ("calibration", state.EstimatedCalibration),
            ("load", state.EstimatedLoad),
            ("interval", state.TelemetryIntervalSeconds));

        var selected = state.Servers.FirstOrDefault(server => server.Entity == state.SelectedServer);
        SelectedServerLabel.Text = selected == null
            ? Loc.GetString("telecom-traffic-console-no-server")
            : Loc.GetString("telecom-traffic-console-selected", ("server", selected.Name));

        RefreshChannels();
        RefreshChannelToggles();
        RefreshGraph();
        RefreshLog();
    }

    private void RefreshChannels()
    {
        if (_state == null)
            return;

        var channels = _state.Logs
            .Select(entry => entry.Channel)
            .Distinct()
            .Order()
            .ToList();

        if (_channels.SequenceEqual(channels))
            return;

        var previous = _selectedChannel;
        _channels.Clear();
        _channels.AddRange(channels);

        GraphChannelFilter.Clear();
        GraphChannelFilter.AddItem(Loc.GetString("telecom-traffic-console-channel-all"), 0);
        for (var i = 0; i < _channels.Count; i++)
            GraphChannelFilter.AddItem(_channels[i], i + 1);

        var selectedIndex = previous == null ? 0 : _channels.IndexOf(previous) + 1;
        if (selectedIndex <= 0)
        {
            selectedIndex = 0;
            _selectedChannel = null;
        }

        GraphChannelFilter.SelectId(selectedIndex);
    }

    private void RefreshChannelToggles()
    {
        ChannelList.Children.Clear();

        if (_state == null)
            return;

        if (_state.SelectedChannels.Count == 0)
        {
            ChannelList.AddChild(new Label
            {
                Text = Loc.GetString("telecom-traffic-console-channels-empty"),
                HorizontalAlignment = HAlignment.Center,
                Margin = new Thickness(0, 12),
                StyleClasses = { "ConsoleText" },
            });
            return;
        }

        foreach (var channel in _state.SelectedChannels)
        {
            var toggleButton = new Button
            {
                Text = channel.Name,
                HorizontalExpand = true,
                ToggleMode = true,
                Pressed = channel.Enabled,
                ModulateSelfOverride = channel.Enabled
                    ? Color.FromHex("#33a73b")
                    : Color.FromHex("#e65454"),
            };

            var capturedChannel = channel.Id;
            toggleButton.OnPressed += _ => OnChannelToggled?.Invoke(capturedChannel);

            ChannelList.AddChild(toggleButton);
        }
    }

    private void RefreshGraph()
    {
        if (_state == null)
            return;

        var received = new int[_state.TrafficBins];
        var sent = new int[_state.TrafficBins];
        var receivedBytes = new int[_state.TrafficBins];
        var sentBytes = new int[_state.TrafficBins];

        var binSeconds = Math.Max(1, _state.TrafficBinSeconds);
        var currentBucket = (int) Math.Floor(_state.CurrentTimeSeconds / binSeconds);

        foreach (var entry in _state.Logs)
        {
            if (_selectedChannel != null && entry.Channel != _selectedChannel)
                continue;

            var successful = IsSuccessful(entry.Status);
            if (successful && !SuccessfulFilter.Pressed ||
                !successful && !FailedFilter.Pressed)
            {
                continue;
            }

            var entryBucket = (int) Math.Floor(entry.TimestampSeconds / binSeconds);
            var age = currentBucket - entryBucket;

            if (age < 0 || age >= _state.TrafficBins)
                continue;

            var bin = _state.TrafficBins - 1 - age;

            received[bin]++;
            receivedBytes[bin] += entry.MessageLength;

            if (successful)
            {
                sent[bin]++;
                sentBytes[bin] += entry.MessageLength;
            }
        }

        TrafficGraph.SetTraffic(received, sent, receivedBytes, sentBytes);

        var receivedTotal = received.Sum();
        var sentTotal = sent.Sum();
        TrafficStatsLabel.Text = Loc.GetString(
            "telecom-traffic-console-graph-stats",
            ("received", receivedTotal),
            ("sent", sentTotal),
            ("failed", receivedTotal - sentTotal),
            ("seconds", _state.TrafficBins * _state.TrafficBinSeconds));
    }

    private void RefreshLog()
    {
        if (_state == null)
            return;

        var oldScroll = LogScroll.GetScrollValue();
        LogContainer.Children.Clear();

        var search = LogSearch.Text.Trim();
        var shown = 0;

        foreach (var entry in _state.Logs)
        {
            var successful = IsSuccessful(entry.Status);
            if (_logOutcomeFilter == LogOutcomeFilter.Successful && !successful ||
                _logOutcomeFilter == LogOutcomeFilter.Failed && successful ||
                !MatchesSearch(entry, search))
            {
                continue;
            }

            var color = entry.Status switch
            {
                TelecomSignalStatus.Routed => Color.FromHex("#45e67b"),
                TelecomSignalStatus.Degraded => Color.FromHex("#e6b845"),
                TelecomSignalStatus.Garbled => Color.FromHex("#e6b845"),
                _ => Color.FromHex("#e65454"),
            };

            var label = new RichTextLabel
            {
                HorizontalExpand = true,
                MaxWidth = 620,
                HorizontalAlignment = HAlignment.Left,
                VerticalAlignment = VAlignment.Top,
                Margin = new Thickness(4, 1),
                ModulateSelfOverride = color,
            };

            var entryText = Loc.GetString(
                string.IsNullOrEmpty(entry.Message)
                    ? "telecom-traffic-console-log-entry-lost"
                    : "telecom-traffic-console-log-entry-header",
                ("time", entry.Timestamp),
                ("status", Loc.GetString($"telecom-traffic-status-{entry.Status.ToString().ToLowerInvariant()}")),
                ("channel", entry.Channel),
                ("size", entry.MessageLength),
                ("quality", entry.SignalQuality),
                ("load", entry.LoadPercent),
                ("latency", entry.LatencyMilliseconds));

            if (!string.IsNullOrEmpty(entry.Message))
            {
                entryText += "\n" + Loc.GetString(
                    "telecom-traffic-console-log-entry-message",
                    ("message", entry.Message));
            }

            label.SetMessage(FormattedMessage.FromUnformatted(entryText));
            LogContainer.AddChild(label);
            shown++;
        }

        if (shown == 0)
        {
            var empty = new Label
            {
                Text = Loc.GetString("telecom-traffic-console-log-empty"),
                HorizontalAlignment = HAlignment.Center,
                Margin = new Thickness(0, 12),
            };
            empty.AddStyleClass("ConsoleText");
            LogContainer.AddChild(empty);
        }

        LogTitleLabel.Text = Loc.GetString(
            "telecom-traffic-console-log-title",
            ("shown", shown),
            ("total", _state.Logs.Count));

        LogScroll.SetScrollValue(LiveLogButton.Pressed ? Vector2.Zero : oldScroll);
    }

    private static bool IsSuccessful(TelecomSignalStatus status)
    {
        return status is TelecomSignalStatus.Routed or TelecomSignalStatus.Degraded or TelecomSignalStatus.Garbled;
    }

    private static bool MatchesSearch(TelecomTrafficLogInfo entry, string search)
    {
        if (string.IsNullOrWhiteSpace(search))
            return true;

        return entry.Channel.Contains(search, StringComparison.OrdinalIgnoreCase) ||
               entry.Message.Contains(search, StringComparison.OrdinalIgnoreCase) ||
               Loc.GetString($"telecom-traffic-status-{entry.Status.ToString().ToLowerInvariant()}")
                   .Contains(search, StringComparison.OrdinalIgnoreCase);
    }

    private void OnServerListSelected(ItemList.ItemListSelectedEventArgs args)
    {
        if (args.ItemList[args.ItemIndex].Metadata is NetEntity server)
            OnServerSelected?.Invoke(server);
    }
}
