using Content.Shared._Onyx.Telecommunications;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;
using System.Linq;
using System.Numerics;

namespace Content.Client._Onyx.Telecommunications;

[GenerateTypedNameReferences]
public sealed partial class TelecomTrafficConsoleWindow : DefaultWindow
{
    private enum LogOutcomeFilter : byte
    {
        All,
        Successful,
        Failed,
    }

    public event Action<NetEntity>? OnServerSelected;
    public event Action<bool>? OnRoutingToggled;
    public event Action<string>? OnChannelToggled;

    private TelecomTrafficConsoleState? _state;
    private readonly List<string> _channels = [];
    private string? _selectedChannel;
    private LogOutcomeFilter _logOutcomeFilter;
    private bool _routingEnabled;

    public TimeSpan CurrentTime;

    public TelecomTrafficConsoleWindow()
    {
        RobustXamlLoader.Load(this);

        RightTabs.SetTabTitle(0, Loc.GetString("telecom-traffic-console-tab-traffic"));
        RightTabs.SetTabTitle(1, Loc.GetString("telecom-traffic-console-tab-hardware"));

        ServerList.OnItemSelected += OnServerListSelected;
        RoutingButton.OnPressed += _ => OnRoutingToggled?.Invoke(!_routingEnabled);

        GraphChannelFilter.OnItemSelected += args =>
        {
            GraphChannelFilter.SelectId(args.Id);
            _selectedChannel = args.Id == 0 ? null : _channels[args.Id - 1];
            RefreshGraph();
        };

        LogStatusFilter.AddItem(Loc.GetString("telecom-traffic-console-log-filter-all"), (int) LogOutcomeFilter.All);
        LogStatusFilter.AddItem(Loc.GetString("telecom-traffic-console-log-filter-successful"), (int) LogOutcomeFilter.Successful);
        LogStatusFilter.AddItem(Loc.GetString("telecom-traffic-console-log-filter-failed"), (int) LogOutcomeFilter.Failed);
        LogStatusFilter.SelectId((int) LogOutcomeFilter.All);
        LogStatusFilter.OnItemSelected += args =>
        {
            LogStatusFilter.SelectId(args.Id);
            _logOutcomeFilter = (LogOutcomeFilter) args.Id;
            RefreshLog();
        };

        SuccessfulFilter.OnToggled += _ => RefreshGraph();
        FailedFilter.OnToggled += _ => RefreshGraph();
        LiveLogButton.OnToggled += _ =>
        {
            if (LiveLogButton.Pressed)
                LogScroll.SetScrollValue(Vector2.Zero);
        };
        LogSearch.OnTextChanged += _ => RefreshLog();
        LogContainer.OnResized += UpdateLogEntryWidths;
    }

    public void UpdateState(TelecomTrafficConsoleState state)
    {
        _state = state;

        ServerList.OnItemSelected -= OnServerListSelected;
        ServerList.Clear();

        foreach (var server in state.Servers)
        {
            var item = ServerList.AddItem($"{server.Name}");
            item.Metadata = server.Entity;
            item.Selected = state.SelectedServer == server.Entity;
        }

        ServerList.OnItemSelected += OnServerListSelected;

        ServerCountLabel.Text = Loc.GetString(
            "telecom-traffic-console-servers",
            ("count", state.Servers.Count));

        _routingEnabled = state.RoutingEnabled;
        RoutingButton.Text = Loc.GetString(
            _routingEnabled
                ? "telecom-traffic-console-disable-routing"
                : "telecom-traffic-console-enable-routing");
        RoutingButton.Disabled = state.SelectedServer == null;

        RoutingStatusLabel.Text = Loc.GetString(
            _routingEnabled
                ? "telecom-traffic-console-routing-online"
                : "telecom-traffic-console-routing-offline");
        RoutingStatusLabel.FontColorOverride = _routingEnabled
            ? Color.FromHex("#45e67b")
            : Color.FromHex("#e65454");
        DiagnosticStatusLabel.Text = Loc.GetString(
            "telecom-traffic-console-diagnostics",
            ("calibration", state.EstimatedCalibration),
            ("load", state.EstimatedLoad));

        var selected = state.Servers.FirstOrDefault(server => server.Entity == state.SelectedServer);
        SelectedServerLabel.Text = selected == null
            ? Loc.GetString("telecom-traffic-console-no-server")
            : Loc.GetString("telecom-traffic-console-selected", ("server", selected.Name));

        RefreshChannels();
        RefreshChannelToggles();
        RefreshGraph();
        RefreshLog();
        RefreshHardware();
    }

    public void UpdateTelemetry(TelecomTrafficTelemetryMessage telemetry)
    {
        DiagnosticStatusLabel.Text = Loc.GetString(
            "telecom-traffic-console-diagnostics",
            ("calibration", telemetry.EstimatedQuality),
            ("load", telemetry.EstimatedLoad));

        if (_state == null)
            return;

        _state.Hardware.Clear();
        _state.Hardware.AddRange(telemetry.Hardware);
        RefreshHardware();
    }

    private void RefreshHardware()
    {
        HardwareList.Children.Clear();

        if (_state == null || _state.Hardware.Count == 0)
        {
            HardwareList.AddChild(new Label
            {
                Text = Loc.GetString("telecom-traffic-console-hardware-empty"),
                HorizontalAlignment = HAlignment.Center,
                Margin = new Thickness(0, 16),
                StyleClasses = { "ConsoleText" },
            });
            return;
        }

        foreach (var hardware in _state.Hardware)
        {
            var panel = new PanelContainer
            {
                HorizontalExpand = true,
                PanelOverride = new Robust.Client.Graphics.StyleBoxFlat
                {
                    BackgroundColor = Color.FromHex("#0a1812"),
                    BorderColor = GetHardwareColor(hardware),
                    BorderThickness = new Thickness(1),
                },
            };

            var content = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Vertical,
                Margin = new Thickness(9, 7),
                SeparationOverride = 3,
            };

            var typeKey = hardware.Type.ToString().ToLowerInvariant();
            content.AddChild(new Label
            {
                Text = Loc.GetString(
                    "telecom-traffic-console-hardware-title",
                    ("type", Loc.GetString($"telecom-traffic-console-hardware-{typeKey}")),
                    ("index", hardware.Index)),
                StyleClasses = { "ConsoleSubHeading" },
            });

            var state = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Horizontal,
                SeparationOverride = 18,
            };

            state.AddChild(MakeHardwareLabel(
                Loc.GetString(
                    hardware.Powered
                        ? "telecom-traffic-console-hardware-powered"
                        : "telecom-traffic-console-hardware-unpowered"),
                hardware.Powered ? Color.FromHex("#45e67b") : Color.FromHex("#e65454")));

            if (hardware.Calibration >= 0)
            {
                state.AddChild(MakeHardwareLabel(
                    Loc.GetString(
                        "telecom-traffic-console-hardware-calibration",
                        ("value", hardware.Calibration)),
                    GetPercentColor(hardware.Calibration)));
            }

            if (hardware.Wear >= 0)
            {
                state.AddChild(MakeHardwareLabel(
                    Loc.GetString(
                        "telecom-traffic-console-hardware-wear",
                        ("value", hardware.Wear)),
                    GetPercentColor(hardware.Wear)));
            }

            if (hardware.LoadPercent >= 0)
            {
                state.AddChild(MakeHardwareLabel(
                    Loc.GetString(
                        "telecom-traffic-console-hardware-load",
                        ("value", hardware.LoadPercent)),
                    GetLoadColor(hardware.LoadPercent)));
            }

            content.AddChild(state);
            panel.AddChild(content);
            HardwareList.AddChild(panel);
        }
    }

    private static Label MakeHardwareLabel(string text, Color color)
    {
        return new Label
        {
            Text = text,
            FontColorOverride = color,
            StyleClasses = { "ConsoleText" },
        };
    }

    private static Color GetHardwareColor(TelecomHardwareInfo hardware)
    {
        if (!hardware.Powered ||
            hardware.Calibration is >= 0 and < 40 ||
            hardware.Wear is >= 0 and < 40 ||
            hardware.LoadPercent is >= 100)
        {
            return Color.FromHex("#e65454");
        }

        if (hardware.Calibration is >= 0 and < 70 ||
            hardware.Wear is >= 0 and < 70 ||
            hardware.LoadPercent is >= 75)
        {
            return Color.FromHex("#e6b845");
        }

        return Color.FromHex("#56c987");
    }

    private static Color GetPercentColor(int value)
    {
        return value switch
        {
            >= 70 => Color.FromHex("#45e67b"),
            >= 40 => Color.FromHex("#e6b845"),
            _ => Color.FromHex("#e65454"),
        };
    }

    private static Color GetLoadColor(int value)
    {
        return value switch
        {
            >= 100 => Color.FromHex("#e65454"),
            >= 75 => Color.FromHex("#e6b845"),
            _ => Color.FromHex("#45e67b"),
        };
    }

    private void RefreshChannels()
    {
        if (_state == null)
            return;

        var channels = _state.Logs
            .Select(entry => entry.Channel)
            .Distinct()
            .Order()
            .ToList();

        if (_channels.SequenceEqual(channels))
            return;

        var previous = _selectedChannel;
        _channels.Clear();
        _channels.AddRange(channels);

        GraphChannelFilter.Clear();
        GraphChannelFilter.AddItem(Loc.GetString("telecom-traffic-console-channel-all"), 0);
        for (var i = 0; i < _channels.Count; i++)
            GraphChannelFilter.AddItem(_channels[i], i + 1);

        var selectedIndex = previous == null ? 0 : _channels.IndexOf(previous) + 1;
        if (selectedIndex <= 0)
        {
            selectedIndex = 0;
            _selectedChannel = null;
        }

        GraphChannelFilter.SelectId(selectedIndex);
    }

    private void RefreshChannelToggles()
    {
        ChannelList.Children.Clear();

        if (_state == null)
            return;

        if (_state.SelectedChannels.Count == 0)
        {
            ChannelList.AddChild(new Label
            {
                Text = Loc.GetString("telecom-traffic-console-channels-empty"),
                HorizontalAlignment = HAlignment.Center,
                Margin = new Thickness(0, 12),
                StyleClasses = { "ConsoleText" },
            });
            return;
        }

        foreach (var channel in _state.SelectedChannels)
        {
            var toggleButton = new Button
            {
                Text = channel.Name,
                HorizontalExpand = true,
                ToggleMode = true,
                Pressed = channel.Enabled,
                ModulateSelfOverride = channel.Enabled
                    ? Color.FromHex("#33a73b")
                    : Color.FromHex("#e65454"),
            };

            var capturedChannel = channel.Id;
            toggleButton.OnPressed += _ => OnChannelToggled?.Invoke(capturedChannel);

            ChannelList.AddChild(toggleButton);
        }
    }

    private void RefreshGraph()
    {
        if (_state == null)
            return;

        var received = new int[_state.TrafficBins];
        var sent = new int[_state.TrafficBins];
        var receivedBytes = new int[_state.TrafficBins];
        var sentBytes = new int[_state.TrafficBins];

        var binSeconds = Math.Max(1, _state.TrafficBinSeconds);
        var currentBucket = (int) Math.Floor(_state.CurrentTimeSeconds / binSeconds);

        foreach (var entry in _state.Logs)
        {
            if (_selectedChannel != null && entry.Channel != _selectedChannel)
                continue;

            var successful = IsSuccessful(entry.Status);
            if (successful && !SuccessfulFilter.Pressed ||
                !successful && !FailedFilter.Pressed)
            {
                continue;
            }

            var entryBucket = (int) Math.Floor(entry.TimestampSeconds / binSeconds);
            var age = currentBucket - entryBucket;

            if (age < 0 || age >= _state.TrafficBins)
                continue;

            var bin = _state.TrafficBins - 1 - age;

            received[bin]++;
            receivedBytes[bin] += entry.MessageLength;

            if (successful)
            {
                sent[bin]++;
                sentBytes[bin] += entry.MessageLength;
            }
        }

        TrafficGraph.SetTraffic(received, sent, receivedBytes, sentBytes);

        var receivedTotal = received.Sum();
        var sentTotal = sent.Sum();
        TrafficStatsLabel.Text = Loc.GetString(
            "telecom-traffic-console-graph-stats",
            ("received", receivedTotal),
            ("sent", sentTotal),
            ("failed", receivedTotal - sentTotal),
            ("seconds", _state.TrafficBins * _state.TrafficBinSeconds));
    }

    private void RefreshLog()
    {
        if (_state == null)
            return;

        var oldScroll = LogScroll.GetScrollValue();
        LogContainer.Children.Clear();

        var search = LogSearch.Text.Trim();
        var shown = 0;

        foreach (var entry in _state.Logs)
        {
            var successful = IsSuccessful(entry.Status);
            if (_logOutcomeFilter == LogOutcomeFilter.Successful && !successful ||
                _logOutcomeFilter == LogOutcomeFilter.Failed && successful ||
                !MatchesSearch(entry, search))
            {
                continue;
            }

            var color = entry.Status switch
            {
                TelecomSignalStatus.Routed => Color.FromHex("#45e67b"),
                TelecomSignalStatus.Degraded => Color.FromHex("#e6b845"),
                TelecomSignalStatus.Garbled => Color.FromHex("#e6b845"),
                _ => Color.FromHex("#e65454"),
            };

            var label = new RichTextLabel
            {
                HorizontalExpand = true,
                HorizontalAlignment = HAlignment.Stretch,
                VerticalAlignment = VAlignment.Top,
                Margin = new Thickness(4, 1),
                ModulateSelfOverride = color,
            };

            var entryText = Loc.GetString(
                string.IsNullOrEmpty(entry.Message)
                    ? "telecom-traffic-console-log-entry-lost"
                    : "telecom-traffic-console-log-entry-header",
                ("time", entry.Timestamp),
                ("status", Loc.GetString($"telecom-traffic-status-{entry.Status.ToString().ToLowerInvariant()}")),
                ("channel", entry.Channel),
                ("size", entry.MessageLength),
                ("quality", entry.SignalQuality),
                ("load", entry.LoadPercent),
                ("latency", entry.LatencyMilliseconds));

            if (!string.IsNullOrEmpty(entry.Message))
            {
                entryText += "\n" + Loc.GetString(
                    "telecom-traffic-console-log-entry-message",
                    ("message", entry.Message));
            }

            label.SetMessage(FormattedMessage.FromUnformatted(entryText));
            LogContainer.AddChild(label);
            shown++;
        }

        if (shown == 0)
        {
            var empty = new Label
            {
                Text = Loc.GetString("telecom-traffic-console-log-empty"),
                HorizontalAlignment = HAlignment.Center,
                Margin = new Thickness(0, 12),
            };
            empty.AddStyleClass("ConsoleText");
            LogContainer.AddChild(empty);
        }

        LogTitleLabel.Text = Loc.GetString(
            "telecom-traffic-console-log-title",
            ("shown", shown),
            ("total", _state.Logs.Count));

        UpdateLogEntryWidths();
        LogScroll.SetScrollValue(LiveLogButton.Pressed ? Vector2.Zero : oldScroll);
    }

    private void UpdateLogEntryWidths()
    {
        // RichTextLabel wraps against the width it receives during measurement.
        // Give every entry the actual viewport width so resizing the window
        // reflows the text instead of leaving an oversized, clipped line.
        var width = LogContainer.Size.X - 8f;
        if (width <= 0f)
            return;

        foreach (var label in LogContainer.Children.OfType<RichTextLabel>())
        {
            if (MathHelper.CloseTo(label.SetWidth, width))
                continue;

            label.SetWidth = width;
        }
    }

    private static bool IsSuccessful(TelecomSignalStatus status)
    {
        return status is TelecomSignalStatus.Routed or TelecomSignalStatus.Degraded or TelecomSignalStatus.Garbled;
    }

    private static bool MatchesSearch(TelecomTrafficLogInfo entry, string search)
    {
        if (string.IsNullOrWhiteSpace(search))
            return true;

        return entry.Channel.Contains(search, StringComparison.OrdinalIgnoreCase) ||
               entry.Message.Contains(search, StringComparison.OrdinalIgnoreCase) ||
               Loc.GetString($"telecom-traffic-status-{entry.Status.ToString().ToLowerInvariant()}")
                   .Contains(search, StringComparison.OrdinalIgnoreCase);
    }

    private void OnServerListSelected(ItemList.ItemListSelectedEventArgs args)
    {
        if (args.ItemList[args.ItemIndex].Metadata is NetEntity server)
            OnServerSelected?.Invoke(server);
    }
}
