using Content.Client._Onyx.Discord;
using Content.Shared.CCVar;
using JetBrains.Annotations;
using Linguini.Bundle.Errors;
using Robust.Client.AutoGenerated;
using Robust.Client.Player;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Configuration;
using Robust.Shared.Utility;

namespace Content.Client.Lobby.UI;

[GenerateTypedNameReferences]
[UsedImplicitly]
public sealed partial class DiscordLinkWindow : DefaultWindow
{
    [Dependency] private readonly IClipboardManager _clipboard = default!;
    [Dependency] private readonly IPlayerManager _player = default!;
    [Dependency] private readonly DiscordIdManager _discordIdManager = default!;
    [Dependency] private readonly IUriOpener _uriOpener = default!;
    [Dependency] private readonly IConfigurationManager _cfg = default!;
    private readonly string _defaultChannelLink = "https://discord.com/channels/1474158623834898648/1488907777941307453";
    private string? _discordId;
    private string? _discordUsername;
    private string? _linkCode;
    private string _channelLink = "";
    private bool _isLinked = false;
    private bool _forcedMode;
    private bool _forceClose;

    private const string UnknownString = "UNKNOWN";

    public DiscordLinkWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        var channelString = _cfg.GetCVar(CCVars.DiscordLinkChannel);
        _channelLink = string.IsNullOrWhiteSpace(channelString) ? _defaultChannelLink : channelString;

        CopyCodeButton.OnPressed += _ =>
        {
            _clipboard.SetText(_linkCode ?? UnknownString);
        };

        OpenDiscordButton.OnPressed += _ =>
        {
            _uriOpener.OpenUri(_channelLink);
        };

        CopyInstructionButton.OnPressed += _ =>
        {
            if (InstructionText.Text != null)
                _clipboard.SetText(InstructionText.Text);
            else
                _clipboard.SetText("");
        };

        UnlinkDiscordButton.OnPressed += _ =>
        {
            _discordIdManager.RequestUnlink();
        };

        _discordIdManager.DiscordInfoUpdated += UpdateStatus;

        UpdateStatus();
    }

    public void SetForcedMode(bool forcedMode)
    {
        _forcedMode = forcedMode;
        if (_forcedMode)
            CloseButton.Visible = false;
    }

    public void ForceClose()
    {
        _forceClose = true;
        Close();
    }

    protected override void Opened()
    {
        base.Opened();

        if (_forcedMode)
        {
            UserInterfaceManager.PushModal(this);
            MoveToFront();
        }

        _discordIdManager.RequestDiscordInfo();
        UpdateStatus();
    }

    protected override void ModalRemoved()
    {
        base.ModalRemoved();

        if (_forcedMode && !_forceClose && IsOpen && !_isLinked)
            UserInterfaceManager.PushModal(this);
    }


    private void CheckLinkDiscord()
    {
        _discordId = null;
        _discordUsername = null;
        _linkCode = null;
        _isLinked = false;

        if (_discordIdManager.TryGetDiscordId(out var discordId))
        {
            _discordId = discordId;
            _isLinked = true;
        }

        if (_isLinked && _discordIdManager.TryGetDiscordUsername(out var discordUsername))
        {
            _discordUsername = discordUsername;
        }

        if (_discordIdManager.TryGetLinkCode(out var linkCode))
            _linkCode = linkCode;
    }

    private void UpdateStatus()
    {
        CheckLinkDiscord();

        if (_isLinked)
        {
            var icName = _player.LocalSession?.Name ?? UnknownString;

            var lines = new List<string>
            {
                Loc.GetString("ui-lobby-discord-link-success-line1"),
                Loc.GetString("ui-lobby-discord-link-success-line2", ("username", _discordUsername ?? "UNKNOWN"), ("discordId", _discordId ?? "UNKNOWN")),
                Loc.GetString("ui-lobby-discord-link-success-line3", ("icName", icName))
            };

            var message = new FormattedMessage();
            message.AddMarkupOrThrow(string.Join("\n", lines));
            SuccessRichText.SetMessage(message);

            InstructionContainer.Visible = false;
            SuccessContainer.Visible = true;
        }
        else
        {
            var instructionLines = new List<string>
            {
                Loc.GetString("ui-lobby-discord-link-instructions-line1"),
                Loc.GetString("ui-lobby-discord-link-instructions-line2", ("code", _linkCode ?? UnknownString)),
                Loc.GetString("ui-lobby-discord-link-instructions-line3", ("channelLink", _channelLink)),
                Loc.GetString("ui-lobby-discord-link-instructions-line4")
            };

            var instructionMessage = new FormattedMessage();
            instructionMessage.AddMarkupOrThrow(string.Join("\n", instructionLines));
            InstructionText.SetMessage(instructionMessage);

            InstructionContainer.Visible = true;
            SuccessContainer.Visible = false;
        }
    }

    protected override void Dispose(bool disposing)
    {
        if (disposing)
            _discordIdManager.DiscordInfoUpdated -= UpdateStatus;

        base.Dispose(disposing);
    }

    public override void Close()
    {
        if (_forcedMode && !_forceClose && !_isLinked)
            return;

        base.Close();
    }
}
