using System;
using System.Linq;
using Content.Shared._Onyx.Surgery.Augments;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.GameObjects;
using Robust.Shared.Maths;
using System.Text;
using static Robust.Client.UserInterface.Controls.BoxContainer;
using FancyWindow = Content.Client.UserInterface.Controls.FancyWindow;

namespace Content.Client._Onyx.Surgery.Augments;

[GenerateTypedNameReferences]
public sealed partial class NeuroInterfaceWindow : FancyWindow
{
    private sealed class AugmentGroup
    {
        public NeuroInterfaceBodyCategory Category;
        public string PartName;
        public List<NeuroInterfaceAugmentEntry> Entries;

        public AugmentGroup(
            NeuroInterfaceBodyCategory category,
            string partName,
            List<NeuroInterfaceAugmentEntry> entries)
        {
            Category = category;
            PartName = partName;
            Entries = entries;
        }
    }

    public event Action<NetEntity, bool>? OnToggleRequested;
    public event Action<NeuroInterfaceBulkTarget, bool>? OnBulkToggleRequested;

    private readonly IEntityManager _entityManager;
    private List<NeuroInterfaceAugmentEntry>? _cachedAugments;

    private static readonly StyleBoxFlat EnabledBackground = new()
    {
        BackgroundColor = new Color(50, 140, 50, 95),
        BorderColor = new Color(120, 210, 120, 170),
        BorderThickness = new Thickness(1),
        ContentMarginLeftOverride = 8,
        ContentMarginRightOverride = 8,
        ContentMarginTopOverride = 4,
        ContentMarginBottomOverride = 4,
    };

    private static readonly StyleBoxFlat DisabledBackground = new()
    {
        BackgroundColor = new Color(160, 55, 55, 95),
        BorderColor = new Color(220, 120, 120, 170),
        BorderThickness = new Thickness(1),
        ContentMarginLeftOverride = 8,
        ContentMarginRightOverride = 8,
        ContentMarginTopOverride = 4,
        ContentMarginBottomOverride = 4,
    };

    private static readonly StyleBoxFlat DeactivatedBackground = new()
    {
        BackgroundColor = new Color(175, 150, 45, 95),
        BorderColor = new Color(235, 210, 120, 170),
        BorderThickness = new Thickness(1),
        ContentMarginLeftOverride = 8,
        ContentMarginRightOverride = 8,
        ContentMarginTopOverride = 4,
        ContentMarginBottomOverride = 4,
    };

    private static readonly StyleBoxFlat NoPowerBackground = new()
    {
        BackgroundColor = new Color(45, 95, 180, 105),
        BorderColor = new Color(125, 185, 255, 185),
        BorderThickness = new Thickness(1),
        ContentMarginLeftOverride = 8,
        ContentMarginRightOverride = 8,
        ContentMarginTopOverride = 4,
        ContentMarginBottomOverride = 4,
    };

    private static readonly StyleBoxFlat NeuroLoadSafeBar = new()
    {
        BackgroundColor = new Color(70, 180, 85, 220),
        BorderColor = new Color(120, 210, 120, 185),
        BorderThickness = new Thickness(1),
    };

    private static readonly StyleBoxFlat NeuroLoadWarnBar = new()
    {
        BackgroundColor = new Color(215, 180, 70, 220),
        BorderColor = new Color(235, 210, 120, 185),
        BorderThickness = new Thickness(1),
    };

    private static readonly StyleBoxFlat NeuroLoadCriticalBar = new()
    {
        BackgroundColor = new Color(200, 70, 70, 220),
        BorderColor = new Color(220, 120, 120, 185),
        BorderThickness = new Thickness(1),
    };

    private const string UnknownPartLocKey = "augment-examine-unknown-part";
    private const string UnknownDescriptionLocKey = "neuro-interface-tooltip-description-unknown";

    public NeuroInterfaceWindow()
    {
        RobustXamlLoader.Load(this);
        Title = Loc.GetString("neuro-interface-window-title");

        var dependencies = IoCManager.Instance!;
        _entityManager = dependencies.Resolve<IEntityManager>();
        AugmentsHeaderPanel.PanelOverride = new StyleBoxFlat
        {
            BackgroundColor = new Color(70, 74, 112, 220),
            BorderColor = new Color(150, 170, 255, 235),
            BorderThickness = new Thickness(1),
            ContentMarginLeftOverride = 0,
            ContentMarginRightOverride = 0,
            ContentMarginTopOverride = 0,
            ContentMarginBottomOverride = 0,
        };

        DisableImplantsButton.OnPressed += _ => OnBulkToggleRequested?.Invoke(NeuroInterfaceBulkTarget.Implants, false);
        EnableImplantsButton.OnPressed += _ => OnBulkToggleRequested?.Invoke(NeuroInterfaceBulkTarget.Implants, true);
        DisableLimbsButton.OnPressed += _ => OnBulkToggleRequested?.Invoke(NeuroInterfaceBulkTarget.Limbs, false);
        EnableLimbsButton.OnPressed += _ => OnBulkToggleRequested?.Invoke(NeuroInterfaceBulkTarget.Limbs, true);
        DisableAllButton.OnPressed += _ => OnBulkToggleRequested?.Invoke(NeuroInterfaceBulkTarget.All, false);
        EnableAllButton.OnPressed += _ => OnBulkToggleRequested?.Invoke(NeuroInterfaceBulkTarget.All, true);
    }

    public void UpdateState(NeuroInterfaceBuiState state)
    {
        Title = Loc.GetString("neuro-interface-window-title");
        CodeLabel.Text = Loc.GetString("neuro-interface-window-code", ("code", state.HexCode));

        UpdatePowerSourceLabel(state);
        UpdateNeuroLoad(state);
        UpdateBatteryLabel(state);

        if (!AreAugmentsEqual(state.Augments, _cachedAugments))
        {
            RebuildAugments(state.Augments);
            _cachedAugments = CloneEntries(state.Augments);
        }
    }

    private void UpdatePowerSourceLabel(NeuroInterfaceBuiState state)
    {
        var sourceText = Loc.GetString("neuro-interface-window-source-value", ("source", state.PowerSourceName));
        var outputText = Loc.GetString("neuro-interface-window-output-value",
            ("rate", MathF.Round(state.PowerOutputPerSecond, 2)));
        PowerSourceLabel.Text = $"{sourceText}\n{outputText}";
    }

    private void UpdateBatteryLabel(NeuroInterfaceBuiState state)
    {
        if (!state.HasBattery)
        {
            BatteryLabel.Text = Loc.GetString("neuro-interface-window-battery-none");
            return;
        }

        var percent = state.BatteryMax > 0f
            ? Math.Clamp(state.BatteryCurrent / state.BatteryMax * 100f, 0f, 100f)
            : 0f;
        var currentText = state.BatteryCurrent.ToString("0.0");
        var maxText = state.BatteryMax.ToString("0.0");
        var percentText = percent.ToString("0.0");

        var batteryText = Loc.GetString("neuro-interface-window-battery-value",
            ("current", currentText),
            ("max", maxText),
            ("percent", percentText));
        var consumptionText = Loc.GetString("neuro-interface-window-consumption-value",
            ("rate", MathF.Round(state.PowerConsumptionPerSecond, 2)));
        BatteryLabel.Text = $"{batteryText}\n{consumptionText}";
    }

    private void UpdateNeuroLoad(NeuroInterfaceBuiState state)
    {
        var max = Math.Max(state.NeuroLoadMax, 0f);
        var current = Math.Max(state.NeuroLoadCurrent, 0f);
        var barValue = max > 0f ? Math.Clamp(current, 0f, max) : 0f;
        var ratio = max > 0f ? current / max : 0f;

        NeuroLoadTitleLabel.Text = Loc.GetString("neuro-interface-window-neuro-load-title");
        NeuroLoadBar.MinValue = 0f;
        NeuroLoadBar.MaxValue = Math.Max(max, 1f);
        NeuroLoadBar.Value = barValue;
        NeuroLoadBar.ForegroundStyleBoxOverride = ratio switch
        {
            <= 0.5f => NeuroLoadSafeBar,
            <= 0.75f => NeuroLoadWarnBar,
            _ => NeuroLoadCriticalBar,
        };

        NeuroLoadValueLabel.Text = Loc.GetString("neuro-interface-window-neuro-load-value",
            ("current", current.ToString("0.0")),
            ("max", max.ToString("0.0")));
    }

    private void RebuildAugments(List<NeuroInterfaceAugmentEntry> entries)
    {
        AugmentsContainer.RemoveAllChildren();

        foreach (var group in BuildAugmentGroups(entries))
        {
            AugmentsContainer.AddChild(new Label
            {
                Text = group.PartName,
                Margin = new Thickness(0, 6, 0, 2),
            });

            foreach (var entry in group.Entries)
            {
                AugmentsContainer.AddChild(CreateEntryControl(entry));
            }
        }

        if (entries.Count == 0)
            AugmentsContainer.AddChild(new Label { Text = Loc.GetString("neuro-interface-window-no-augments") });
    }

    private static List<NeuroInterfaceAugmentEntry> CloneEntries(List<NeuroInterfaceAugmentEntry> entries)
    {
        var copy = new List<NeuroInterfaceAugmentEntry>(entries.Count);
        foreach (var entry in entries)
        {
            copy.Add(new NeuroInterfaceAugmentEntry(
                entry.Augment,
                entry.Part,
                entry.Category,
                entry.Name,
                entry.Enabled,
                entry.CanToggle,
                entry.CanConfigure,
                entry.Status,
                entry.Description,
                entry.PassivePower,
                entry.ActivePower,
                entry.PassiveNeuroLoad,
                entry.ActiveNeuroLoad));
        }

        return copy;
    }

    private static bool AreAugmentsEqual(List<NeuroInterfaceAugmentEntry> current, List<NeuroInterfaceAugmentEntry>? cached)
    {
        if (cached == null || current.Count != cached.Count)
            return false;

        for (var i = 0; i < current.Count; i++)
        {
            var a = current[i];
            var b = cached[i];
            if (a.Augment != b.Augment
                || a.Part != b.Part
                || a.Category != b.Category
                || a.Name != b.Name
                || a.Enabled != b.Enabled
                || a.CanToggle != b.CanToggle
                || a.CanConfigure != b.CanConfigure
                || a.Status != b.Status
                || a.Description != b.Description
                || MathF.Abs(a.PassivePower - b.PassivePower) > 0.0001f
                || MathF.Abs(a.ActivePower - b.ActivePower) > 0.0001f
                || MathF.Abs(a.PassiveNeuroLoad - b.PassiveNeuroLoad) > 0.0001f
                || MathF.Abs(a.ActiveNeuroLoad - b.ActiveNeuroLoad) > 0.0001f)
            {
                return false;
            }
        }

        return true;
    }

    private List<AugmentGroup> BuildAugmentGroups(List<NeuroInterfaceAugmentEntry> entries)
    {
        var partNameCache = new Dictionary<EntityUid, string>();
        var groups = entries
            .GroupBy(entry => _entityManager.GetEntity(entry.Part))
            .Select(group =>
            {
                var first = group.First();
                return new AugmentGroup(
                    first.Category,
                    GetPartNameCached(group.Key, partNameCache),
                    group.ToList());
            })
            .ToList();

        groups.Sort((a, b) =>
        {
            var categoryCompare = GetCategoryRank(a.Category).CompareTo(GetCategoryRank(b.Category));
            if (categoryCompare != 0)
                return categoryCompare;

            return string.Compare(a.PartName, b.PartName, StringComparison.OrdinalIgnoreCase);
        });

        return groups;
    }

    private static int GetCategoryRank(NeuroInterfaceBodyCategory category)
    {
        return category switch
        {
            NeuroInterfaceBodyCategory.Head => 0,
            NeuroInterfaceBodyCategory.Torso => 1,
            NeuroInterfaceBodyCategory.RightArm => 2,
            NeuroInterfaceBodyCategory.LeftArm => 3,
            NeuroInterfaceBodyCategory.RightHand => 4,
            NeuroInterfaceBodyCategory.LeftHand => 5,
            NeuroInterfaceBodyCategory.Groin => 6,
            NeuroInterfaceBodyCategory.RightLeg => 7,
            NeuroInterfaceBodyCategory.LeftLeg => 8,
            NeuroInterfaceBodyCategory.RightFoot => 9,
            NeuroInterfaceBodyCategory.LeftFoot => 10,
            _ => int.MaxValue,
        };
    }

    private string GetPartNameCached(EntityUid partUid, Dictionary<EntityUid, string> cache)
    {
        if (cache.TryGetValue(partUid, out var cached))
            return cached;

        var value = GetPartName(partUid);
        cache[partUid] = value;
        return value;
    }

    private string GetPartName(EntityUid partUid)
    {
        if (!_entityManager.EntityExists(partUid))
            return Loc.GetString(UnknownPartLocKey);

        if (_entityManager.TryGetComponent<MetaDataComponent>(partUid, out var meta)
            && !string.IsNullOrWhiteSpace(meta.EntityName))
        {
            return meta.EntityName;
        }

        return Loc.GetString(UnknownPartLocKey);
    }

    private PanelContainer CreateEntryControl(NeuroInterfaceAugmentEntry entry)
    {
        var row = new BoxContainer
        {
            Orientation = LayoutOrientation.Horizontal,
            SeparationOverride = 6,
            HorizontalExpand = true,
        };

        var infoButton = new Button
        {
            Text = "?",
            MinWidth = 24,
            ToolTip = BuildAugmentTooltip(entry),
            StyleBoxOverride = GetStatusBackground(entry.Status),
        };
        row.AddChild(infoButton);

        row.AddChild(new Label
        {
            Text = entry.Name,
            HorizontalExpand = true,
            Margin = new Thickness(6, 0, 0, 0),
        });

        var toggleButton = new Button
        {
            Text = Loc.GetString(entry.Enabled ? "neuro-interface-button-disable" : "neuro-interface-button-enable"),
            Disabled = !entry.CanToggle,
            MinWidth = 90,
            StyleBoxOverride = GetStatusBackground(entry.Status),
        };

        toggleButton.OnPressed += _ => OnToggleRequested?.Invoke(entry.Augment, !entry.Enabled);
        row.AddChild(toggleButton);

        var settingsButton = new Button
        {
            Text = Loc.GetString("neuro-interface-button-settings"),
            Disabled = !entry.CanConfigure,
            MinWidth = 95,
            StyleBoxOverride = GetStatusBackground(entry.Status),
        };

        row.AddChild(settingsButton);

        var panel = new PanelContainer
        {
            PanelOverride = GetStatusBackground(entry.Status),
            Margin = new Thickness(0, 0, 0, 4),
        };

        panel.AddChild(row);
        return panel;
    }

    private string BuildAugmentTooltip(NeuroInterfaceAugmentEntry entry)
    {
        var description = string.IsNullOrWhiteSpace(entry.Description)
            ? Loc.GetString(UnknownDescriptionLocKey)
            : entry.Description;

        var builder = new StringBuilder();
        builder.AppendLine(Loc.GetString(GetStatusTooltipLocKey(entry.Status)));
        builder.AppendLine(Loc.GetString("neuro-interface-tooltip-description", ("description", description)));

        var hasPowerInfo = MathF.Abs(entry.PassivePower) > 0.0001f || MathF.Abs(entry.ActivePower) > 0.0001f;
        if (hasPowerInfo)
        {
            builder.AppendLine(Loc.GetString("neuro-interface-tooltip-power-passive", ("value", entry.PassivePower.ToString("0.0"))));
            builder.AppendLine(Loc.GetString("neuro-interface-tooltip-power-active", ("value", entry.ActivePower.ToString("0.0"))));
        }

        var hasNeuroInfo = MathF.Abs(entry.PassiveNeuroLoad) > 0.0001f || MathF.Abs(entry.ActiveNeuroLoad) > 0.0001f;
        if (hasNeuroInfo)
        {
            builder.AppendLine(Loc.GetString("neuro-interface-tooltip-neuro-passive", ("value", entry.PassiveNeuroLoad.ToString("0.0"))));
            builder.Append(Loc.GetString("neuro-interface-tooltip-neuro-active", ("value", entry.ActiveNeuroLoad.ToString("0.0"))));
        }

        return builder.ToString();
    }

    private static StyleBoxFlat GetStatusBackground(NeuroInterfaceAugmentStatus status)
    {
        return status switch
        {
            NeuroInterfaceAugmentStatus.Enabled => EnabledBackground,
            NeuroInterfaceAugmentStatus.Disabled => DisabledBackground,
            NeuroInterfaceAugmentStatus.Deactivated => DeactivatedBackground,
            NeuroInterfaceAugmentStatus.NoPower => NoPowerBackground,
            _ => DisabledBackground,
        };
    }

    private static string GetStatusTooltipLocKey(NeuroInterfaceAugmentStatus status)
    {
        return status switch
        {
            NeuroInterfaceAugmentStatus.Enabled => "neuro-interface-status-tooltip-enabled",
            NeuroInterfaceAugmentStatus.Disabled => "neuro-interface-status-tooltip-disabled",
            NeuroInterfaceAugmentStatus.Deactivated => "neuro-interface-status-tooltip-deactivated",
            NeuroInterfaceAugmentStatus.NoPower => "neuro-interface-status-tooltip-no-power",
            _ => "neuro-interface-status-tooltip-disabled",
        };
    }

}
