using System;
using System.Numerics;
using System.Linq;
using Content.Shared._Onyx.Surgery.Augments;
using Content.Shared._Shitmed.Medical.Surgery.Wounds;
using Content.Shared._Shitmed.Targeting;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.GameObjects;
using Robust.Shared.Maths;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;
using static Robust.Client.UserInterface.Controls.BoxContainer;
using FancyWindow = Content.Client.UserInterface.Controls.FancyWindow;

namespace Content.Client._Onyx.Surgery.Augments;

[GenerateTypedNameReferences]
public sealed partial class NeuroInterfaceWindow : FancyWindow
{
    public event Action<NetEntity, bool>? OnToggleRequested;

    private readonly IEntityManager _entityManager;
    private readonly SpriteSystem _spriteSystem;
    private EntityUid _spriteViewEntity;

    [ValidatePrototypeId<EntityPrototype>]
    private readonly EntProtoId _bodyView = "AlertSpriteView";

    private static readonly StyleBoxFlat EnabledBackground = new()
    {
        BackgroundColor = new Color(50, 140, 50, 95),
        BorderColor = new Color(120, 210, 120, 170),
        BorderThickness = new Thickness(1),
        ContentMarginLeftOverride = 8,
        ContentMarginRightOverride = 8,
        ContentMarginTopOverride = 4,
        ContentMarginBottomOverride = 4,
    };

    private static readonly StyleBoxFlat DisabledBackground = new()
    {
        BackgroundColor = new Color(160, 55, 55, 95),
        BorderColor = new Color(220, 120, 120, 170),
        BorderThickness = new Thickness(1),
        ContentMarginLeftOverride = 8,
        ContentMarginRightOverride = 8,
        ContentMarginTopOverride = 4,
        ContentMarginBottomOverride = 4,
    };

    private static readonly StyleBoxFlat DeactivatedBackground = new()
    {
        BackgroundColor = new Color(175, 150, 45, 95),
        BorderColor = new Color(235, 210, 120, 170),
        BorderThickness = new Thickness(1),
        ContentMarginLeftOverride = 8,
        ContentMarginRightOverride = 8,
        ContentMarginTopOverride = 4,
        ContentMarginBottomOverride = 4,
    };

    private static readonly NeuroInterfaceBodyCategory[] CategoryOrder =
    {
        NeuroInterfaceBodyCategory.Head,
        NeuroInterfaceBodyCategory.Torso,
        NeuroInterfaceBodyCategory.RightArm,
        NeuroInterfaceBodyCategory.LeftArm,
        NeuroInterfaceBodyCategory.RightHand,
        NeuroInterfaceBodyCategory.LeftHand,
        NeuroInterfaceBodyCategory.Groin,
        NeuroInterfaceBodyCategory.RightLeg,
        NeuroInterfaceBodyCategory.LeftLeg,
        NeuroInterfaceBodyCategory.RightFoot,
        NeuroInterfaceBodyCategory.LeftFoot,
    };

    public NeuroInterfaceWindow()
    {
        RobustXamlLoader.Load(this);
        Title = Loc.GetString("neuro-interface-window-title");

        var dependencies = IoCManager.Instance!;
        _entityManager = dependencies.Resolve<IEntityManager>();
        _spriteSystem = _entityManager.System<SpriteSystem>();
        SetupDollIcon();

        foreach (var button in new[]
        {
            HeadButton, ChestButton, GroinButton,
            RightArmButton, RightHandButton, LeftArmButton, LeftHandButton,
            RightLegButton, RightFootButton, LeftLegButton, LeftFootButton
        })
        {
            button.Disabled = false;
            button.MouseFilter = MouseFilterMode.Ignore;
        }
    }

    protected override void Dispose(bool disposing)
    {
        base.Dispose(disposing);

        if (_spriteViewEntity != EntityUid.Invalid && !_entityManager.Deleted(_spriteViewEntity))
            _entityManager.QueueDeleteEntity(_spriteViewEntity);
    }

    public void UpdateState(NeuroInterfaceBuiState state)
    {
        Title = Loc.GetString("neuro-interface-window-title");
        CodeLabel.Text = Loc.GetString("neuro-interface-window-code", ("code", state.HexCode));

        if (!state.HasBattery)
        {
            BatteryLabel.Text = Loc.GetString("neuro-interface-window-battery-none");
        }
        else
        {
            var percent = state.BatteryMax > 0f
                ? Math.Clamp(state.BatteryCurrent / state.BatteryMax * 100f, 0f, 100f)
                : 0f;

            BatteryLabel.Text = Loc.GetString("neuro-interface-window-battery-value",
                ("current", MathF.Round(state.BatteryCurrent, 1)),
                ("max", MathF.Round(state.BatteryMax, 1)),
                ("percent", MathF.Round(percent, 1)));
        }

        AugmentsContainer.RemoveAllChildren();

        foreach (var category in CategoryOrder)
        {
            var categoryEntries = state.Augments.Where(x => x.Category == category).ToList();
            if (categoryEntries.Count == 0)
                continue;

            AugmentsContainer.AddChild(new Label
            {
                Text = Loc.GetString(GetCategoryLoc(category)),
                Margin = new Thickness(0, 6, 0, 2),
            });

            foreach (var entry in categoryEntries)
            {
                AugmentsContainer.AddChild(CreateEntryControl(entry));
            }
        }

        if (state.Augments.Count == 0)
        {
            AugmentsContainer.AddChild(new Label { Text = Loc.GetString("neuro-interface-window-no-augments") });
        }
    }

    private PanelContainer CreateEntryControl(NeuroInterfaceAugmentEntry entry)
    {
        var row = new BoxContainer
        {
            Orientation = LayoutOrientation.Horizontal,
            SeparationOverride = 6,
            HorizontalExpand = true,
        };

        row.AddChild(new Label
        {
            Text = entry.Name,
            HorizontalExpand = true,
            Margin = new Thickness(6, 0, 0, 0),
        });

        var toggleButton = new Button
        {
            Text = Loc.GetString(entry.Enabled ? "neuro-interface-button-disable" : "neuro-interface-button-enable"),
            Disabled = !entry.CanToggle,
            MinWidth = 90,
        };

        toggleButton.OnPressed += _ => OnToggleRequested?.Invoke(entry.Augment, !entry.Enabled);
        row.AddChild(toggleButton);

        var settingsButton = new Button
        {
            Text = Loc.GetString("neuro-interface-button-settings"),
            Disabled = !entry.CanConfigure,
            MinWidth = 95,
        };

        row.AddChild(settingsButton);

        var panel = new PanelContainer
        {
            PanelOverride = GetStatusBackground(entry.Status),
            Margin = new Thickness(0, 0, 0, 4),
        };

        panel.AddChild(row);
        return panel;
    }

    private static string GetCategoryLoc(NeuroInterfaceBodyCategory category)
    {
        return category switch
        {
            NeuroInterfaceBodyCategory.Head => "neuro-interface-category-head",
            NeuroInterfaceBodyCategory.Torso => "neuro-interface-category-torso",
            NeuroInterfaceBodyCategory.RightArm => "neuro-interface-category-right-arm",
            NeuroInterfaceBodyCategory.LeftArm => "neuro-interface-category-left-arm",
            NeuroInterfaceBodyCategory.RightHand => "neuro-interface-category-right-hand",
            NeuroInterfaceBodyCategory.LeftHand => "neuro-interface-category-left-hand",
            NeuroInterfaceBodyCategory.Groin => "neuro-interface-category-groin",
            NeuroInterfaceBodyCategory.RightLeg => "neuro-interface-category-right-leg",
            NeuroInterfaceBodyCategory.LeftLeg => "neuro-interface-category-left-leg",
            NeuroInterfaceBodyCategory.RightFoot => "neuro-interface-category-right-foot",
            NeuroInterfaceBodyCategory.LeftFoot => "neuro-interface-category-left-foot",
            _ => "neuro-interface-category-torso",
        };
    }

    private static StyleBoxFlat GetStatusBackground(NeuroInterfaceAugmentStatus status)
    {
        return status switch
        {
            NeuroInterfaceAugmentStatus.Enabled => EnabledBackground,
            NeuroInterfaceAugmentStatus.Disabled => DisabledBackground,
            NeuroInterfaceAugmentStatus.Deactivated => DeactivatedBackground,
            _ => DisabledBackground,
        };
    }

    private void SetupDollIcon()
    {
        if (_spriteViewEntity != EntityUid.Invalid && !_entityManager.Deleted(_spriteViewEntity))
            _entityManager.QueueDeleteEntity(_spriteViewEntity);

        _spriteViewEntity = _entityManager.Spawn(_bodyView);

        if (!_entityManager.TryGetComponent<SpriteComponent>(_spriteViewEntity, out var sprite))
            return;

        var parts = new[]
        {
            TargetBodyPart.Head,
            TargetBodyPart.Chest,
            TargetBodyPart.Groin,
            TargetBodyPart.LeftArm,
            TargetBodyPart.LeftHand,
            TargetBodyPart.RightArm,
            TargetBodyPart.RightHand,
            TargetBodyPart.LeftLeg,
            TargetBodyPart.LeftFoot,
            TargetBodyPart.RightLeg,
            TargetBodyPart.RightFoot,
        };

        var layer = 0;
        foreach (var bodyPart in parts)
        {
            var enumName = Enum.GetName(typeof(TargetBodyPart), bodyPart) ?? "Unknown";
            var baseRsiPath = new ResPath($"/Textures/_Shitmed/Interface/Targeting/Status/{enumName.ToLowerInvariant()}.rsi");
            var rsi = new SpriteSpecifier.Rsi(baseRsiPath, $"{enumName.ToLowerInvariant()}_{(int) WoundableSeverity.Healthy}");
            CreateOrAddToLayer(sprite, rsi, layer);
            layer++;
        }

        SpriteView.SetEntity(_spriteViewEntity);
    }

    private void CreateOrAddToLayer(SpriteComponent sprite, SpriteSpecifier rsi, int layer)
    {
        if (!sprite.TryGetLayer(layer, out _))
            sprite.AddLayer(_spriteSystem.Frame0(rsi));
        else
            sprite.LayerSetTexture(layer, _spriteSystem.Frame0(rsi));

        sprite.LayerSetScale(layer, new Vector2(6f, 6f));
    }
}
