using System;
using System.Collections.Generic;
using System.Numerics;
using Content.Shared._Onyx.Surgery.Augments;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.GameObjects;
using Robust.Shared.Maths;
using Robust.Shared.Utility;
using static Robust.Client.UserInterface.Controls.BoxContainer;
using static Robust.Client.UserInterface.Controls.LayoutContainer;
using FancyWindow = Content.Client.UserInterface.Controls.FancyWindow;

namespace Content.Client._Onyx.Surgery.Augments;

[GenerateTypedNameReferences]
public sealed partial class NeuroInterfaceWindow : FancyWindow
{
    private sealed class AugmentGroup
    {
        public NetEntity PartNet;
        public NeuroInterfaceBodyCategory Category;
        public string PartName;
        public List<NeuroInterfaceAugmentEntry> Entries;

        public AugmentGroup(
            NetEntity partNet,
            NeuroInterfaceBodyCategory category,
            string partName,
            List<NeuroInterfaceAugmentEntry> entries)
        {
            PartNet = partNet;
            Category = category;
            PartName = partName;
            Entries = entries;
        }
    }

    private sealed class NeuroInterfaceViewSettings
    {
        public HashSet<NetEntity> CollapsedGroups = new();
        public HashSet<NetEntity> CollapsedAugments = new();
    }

    public event Action<NetEntity, bool>? OnToggleRequested;
    public event Action<NeuroInterfaceBulkTarget, bool>? OnBulkToggleRequested;

    private readonly IEntityManager _entityManager;
    private const int MaxSavedViewSettings = 128;
    private static readonly Dictionary<string, NeuroInterfaceViewSettings> SavedViewSettings = new();
    private static readonly Queue<string> SavedViewSettingsInsertOrder = new();
    private List<NeuroInterfaceAugmentEntry>? _cachedAugments;
    private NeuroInterfaceViewSettings _viewSettings = new();
    private string _settingsKey = string.Empty;

    private static readonly StyleBoxFlat EnabledBackground = new()
    {
        BackgroundColor = new Color(50, 140, 50, 95),
        BorderColor = new Color(120, 210, 120, 170),
        BorderThickness = new Thickness(1),
        ContentMarginLeftOverride = 8,
        ContentMarginRightOverride = 8,
        ContentMarginTopOverride = 4,
        ContentMarginBottomOverride = 4,
    };

    private static readonly StyleBoxFlat DisabledBackground = new()
    {
        BackgroundColor = new Color(160, 55, 55, 95),
        BorderColor = new Color(220, 120, 120, 170),
        BorderThickness = new Thickness(1),
        ContentMarginLeftOverride = 8,
        ContentMarginRightOverride = 8,
        ContentMarginTopOverride = 4,
        ContentMarginBottomOverride = 4,
    };

    private static readonly StyleBoxFlat DeactivatedBackground = new()
    {
        BackgroundColor = new Color(175, 150, 45, 95),
        BorderColor = new Color(235, 210, 120, 170),
        BorderThickness = new Thickness(1),
        ContentMarginLeftOverride = 8,
        ContentMarginRightOverride = 8,
        ContentMarginTopOverride = 4,
        ContentMarginBottomOverride = 4,
    };

    private static readonly StyleBoxFlat NoPowerBackground = new()
    {
        BackgroundColor = new Color(45, 95, 180, 105),
        BorderColor = new Color(125, 185, 255, 185),
        BorderThickness = new Thickness(1),
        ContentMarginLeftOverride = 8,
        ContentMarginRightOverride = 8,
        ContentMarginTopOverride = 4,
        ContentMarginBottomOverride = 4,
    };

    private static readonly StyleBoxFlat EnabledTooltipBackground = new()
    {
        BackgroundColor = new Color(44, 96, 44, 255),
        BorderColor = new Color(92, 150, 92, 255),
        BorderThickness = new Thickness(1),
        ContentMarginLeftOverride = 8,
        ContentMarginRightOverride = 8,
        ContentMarginTopOverride = 6,
        ContentMarginBottomOverride = 6,
    };

    private static readonly StyleBoxFlat DisabledTooltipBackground = new()
    {
        BackgroundColor = new Color(112, 52, 52, 255),
        BorderColor = new Color(168, 102, 102, 255),
        BorderThickness = new Thickness(1),
        ContentMarginLeftOverride = 8,
        ContentMarginRightOverride = 8,
        ContentMarginTopOverride = 6,
        ContentMarginBottomOverride = 6,
    };

    private static readonly StyleBoxFlat DeactivatedTooltipBackground = new()
    {
        BackgroundColor = new Color(118, 102, 52, 255),
        BorderColor = new Color(176, 152, 102, 255),
        BorderThickness = new Thickness(1),
        ContentMarginLeftOverride = 8,
        ContentMarginRightOverride = 8,
        ContentMarginTopOverride = 6,
        ContentMarginBottomOverride = 6,
    };

    private static readonly StyleBoxFlat NoPowerTooltipBackground = new()
    {
        BackgroundColor = new Color(50, 82, 124, 255),
        BorderColor = new Color(96, 136, 182, 255),
        BorderThickness = new Thickness(1),
        ContentMarginLeftOverride = 8,
        ContentMarginRightOverride = 8,
        ContentMarginTopOverride = 6,
        ContentMarginBottomOverride = 6,
    };

    private static readonly StyleBoxFlat CategoryHeaderBackground = new()
    {
        BackgroundColor = new Color(70, 74, 112, 220),
        BorderColor = new Color(150, 170, 255, 235),
        BorderThickness = new Thickness(1),
        ContentMarginLeftOverride = 0,
        ContentMarginRightOverride = 0,
        ContentMarginTopOverride = 0,
        ContentMarginBottomOverride = 0,
    };

    private static readonly StyleBoxFlat NeuroLoadSafeBar = new()
    {
        BackgroundColor = new Color(70, 180, 85, 220),
        BorderColor = new Color(59, 153, 72, 255),
        BorderThickness = new Thickness(2f),
    };

    private static readonly StyleBoxFlat NeuroLoadWarnBar = new()
    {
        BackgroundColor = new Color(215, 180, 70, 220),
        BorderColor = new Color(183, 153, 60, 255),
        BorderThickness = new Thickness(2f),
    };

    private static readonly StyleBoxFlat NeuroLoadCriticalBar = new()
    {
        BackgroundColor = new Color(200, 70, 70, 220),
        BorderColor = new Color(170, 60, 60, 255),
        BorderThickness = new Thickness(2f),
    };

    private static readonly StyleBoxFlat NeuroLoadBackground = new()
    {
        BackgroundColor = new Color(20, 22, 28, 255),
        BorderColor = Color.Transparent,
        BorderThickness = new Thickness(0),
    };

    private const string UnknownPartLocKey = "augment-examine-unknown-part";
    private const string UnknownDescriptionLocKey = "neuro-interface-tooltip-description-unknown";
    private const float TooltipTextMaxWidth = 560;

    public NeuroInterfaceWindow()
    {
        RobustXamlLoader.Load(this);
        Title = Loc.GetString("neuro-interface-window-title");

        var dependencies = IoCManager.Instance!;
        _entityManager = dependencies.Resolve<IEntityManager>();
        AugmentsHeaderPanel.PanelOverride = CategoryHeaderBackground;

        DisableImplantsButton.OnPressed += _ => OnBulkToggleRequested?.Invoke(NeuroInterfaceBulkTarget.Implants, false);
        EnableImplantsButton.OnPressed += _ => OnBulkToggleRequested?.Invoke(NeuroInterfaceBulkTarget.Implants, true);
        DisableLimbsButton.OnPressed += _ => OnBulkToggleRequested?.Invoke(NeuroInterfaceBulkTarget.Limbs, false);
        EnableLimbsButton.OnPressed += _ => OnBulkToggleRequested?.Invoke(NeuroInterfaceBulkTarget.Limbs, true);
        DisableAllButton.OnPressed += _ => OnBulkToggleRequested?.Invoke(NeuroInterfaceBulkTarget.All, false);
        EnableAllButton.OnPressed += _ => OnBulkToggleRequested?.Invoke(NeuroInterfaceBulkTarget.All, true);
        SetupNeuroLoadOverlay();
    }

    public void UpdateState(NeuroInterfaceBuiState state)
    {
        Title = Loc.GetString("neuro-interface-window-title");
        CodeLabel.Text = Loc.GetString("neuro-interface-window-code", ("code", state.HexCode));
        EnsureViewSettings(state.HexCode);

        UpdatePowerSourceLabel(state);
        UpdateNeuroLoad(state);
        UpdateBatteryLabel(state);

        if (!AreAugmentsEqual(state.Augments, _cachedAugments))
        {
            RebuildAugments(state.Augments);
            _cachedAugments = CloneEntries(state.Augments);
        }
    }

    private void UpdatePowerSourceLabel(NeuroInterfaceBuiState state)
    {
        var sourceText = Loc.GetString("neuro-interface-window-source-value", ("source", state.PowerSourceName));
        var outputText = Loc.GetString("neuro-interface-window-output-value",
            ("rate", MathF.Round(state.PowerOutputPerSecond, 2)));
        PowerSourceLabel.Text = string.Concat(sourceText, "\n", outputText);
    }

    private void UpdateBatteryLabel(NeuroInterfaceBuiState state)
    {
        if (!state.HasBattery)
        {
            BatteryLabel.Text = Loc.GetString("neuro-interface-window-battery-none");
            return;
        }

        var percent = state.BatteryMax > 0f
            ? Math.Clamp(state.BatteryCurrent / state.BatteryMax * 100f, 0f, 100f)
            : 0f;
        var currentText = state.BatteryCurrent.ToString("0.0");
        var maxText = state.BatteryMax.ToString("0.0");
        var percentText = percent.ToString("0.0");

        var batteryText = Loc.GetString("neuro-interface-window-battery-value",
            ("current", currentText),
            ("max", maxText),
            ("percent", percentText));
        var consumptionText = Loc.GetString("neuro-interface-window-consumption-value",
            ("rate", MathF.Round(state.PowerConsumptionPerSecond, 2)));
        BatteryLabel.Text = string.Concat(batteryText, "\n", consumptionText);
    }

    private void UpdateNeuroLoad(NeuroInterfaceBuiState state)
    {
        var max = Math.Max(state.NeuroLoadMax, 0f);
        var current = Math.Max(state.NeuroLoadCurrent, 0f);
        var barValue = max > 0f ? Math.Clamp(current, 0f, max) : 0f;

        NeuroLoadTitleLabel.Text = Loc.GetString("neuro-interface-window-neuro-load-title");
        NeuroLoadBar.MinValue = 0f;
        NeuroLoadBar.MaxValue = Math.Max(max, 1f);
        NeuroLoadBar.Value = barValue;
        NeuroLoadBar.BackgroundStyleBoxOverride = NeuroLoadBackground;
        var ratio = max > 0f ? current / max : 0f;
        NeuroLoadBar.ForegroundStyleBoxOverride = ratio switch
        {
            <= 0.75f => NeuroLoadSafeBar,
            <= 0.90f => NeuroLoadWarnBar,
            _ => NeuroLoadCriticalBar,
        };

        NeuroLoadValueLabel.Text = Loc.GetString("neuro-interface-window-neuro-load-value",
            ("current", current.ToString("0.0")),
            ("max", max.ToString("0.0")));
    }

    private void SetupNeuroLoadOverlay()
    {
        SetAnchorPreset(NeuroLoadBar, LayoutPreset.Wide);
        SetAnchorPreset(NeuroLoadValueLabel, LayoutPreset.Wide);

        NeuroLoadValueLabel.SetPositionLast();

        NeuroLoadValueLabel.Align = Label.AlignMode.Left;
        NeuroLoadValueLabel.VAlign = Label.VAlignMode.Center;
        NeuroLoadValueLabel.FontColorOverride = Color.White;
        SetPosition(NeuroLoadValueLabel, new Vector2(6, -1));
    }

    private void EnsureViewSettings(string interfaceCode)
    {
        if (_settingsKey == interfaceCode)
            return;

        _settingsKey = interfaceCode;
        if (!SavedViewSettings.TryGetValue(interfaceCode, out var settings))
        {
            while (SavedViewSettings.Count >= MaxSavedViewSettings && SavedViewSettingsInsertOrder.Count > 0)
            {
                var staleKey = SavedViewSettingsInsertOrder.Dequeue();
                SavedViewSettings.Remove(staleKey);
            }

            settings = new NeuroInterfaceViewSettings();
            SavedViewSettings[interfaceCode] = settings;
            SavedViewSettingsInsertOrder.Enqueue(interfaceCode);
        }

        _viewSettings = settings;
    }

    private void RebuildAugments(List<NeuroInterfaceAugmentEntry> entries)
    {
        AugmentsContainer.RemoveAllChildren();

        foreach (var group in BuildAugmentGroups(entries))
        {
            var groupCollapsed = _viewSettings.CollapsedGroups.Contains(group.PartNet);
            var groupButton = new Button
            {
                Text = GetGroupHeaderText(group.PartName, groupCollapsed),
                HorizontalExpand = true,
                Margin = new Thickness(0, 6, 0, 2),
                TextAlign = Label.AlignMode.Left,
                StyleBoxOverride = CategoryHeaderBackground,
            };
            groupButton.Label.HorizontalAlignment = HAlignment.Left;
            groupButton.Label.Margin = new Thickness(6, 0, 0, 0);
            groupButton.OnPressed += _ =>
            {
                ToggleGroupCollapsed(group.PartNet);
                groupButton.Text = GetGroupHeaderText(group.PartName, _viewSettings.CollapsedGroups.Contains(group.PartNet));
                RebuildAugments(entries);
            };
            AugmentsContainer.AddChild(groupButton);

            if (groupCollapsed)
                continue;

            foreach (var entry in group.Entries)
            {
                AugmentsContainer.AddChild(CreateEntryControl(entry));
            }
        }

        if (entries.Count == 0)
            AugmentsContainer.AddChild(new Label { Text = Loc.GetString("neuro-interface-window-no-augments") });
    }

    private static List<NeuroInterfaceAugmentEntry> CloneEntries(List<NeuroInterfaceAugmentEntry> entries)
    {
        var copy = new List<NeuroInterfaceAugmentEntry>(entries.Count);
        foreach (var entry in entries)
        {
            copy.Add(new NeuroInterfaceAugmentEntry(
                entry.Augment,
                entry.Part,
                entry.Category,
                entry.Name,
                entry.Enabled,
                entry.CanToggle,
                entry.CanConfigure,
                entry.Status,
                entry.Description,
                CloneMetricEntries(entry.PassivePowerEntries),
                CloneMetricEntries(entry.ActivePowerEntries),
                CloneMetricEntries(entry.PassiveNeuroLoadEntries),
                CloneMetricEntries(entry.ActiveNeuroLoadEntries),
                CloneModuleEntries(entry.Modules)));
        }

        return copy;
    }

    private static List<NeuroInterfaceMetricEntry> CloneMetricEntries(List<NeuroInterfaceMetricEntry> entries)
    {
        var copy = new List<NeuroInterfaceMetricEntry>(entries.Count);
        foreach (var entry in entries)
        {
            copy.Add(new NeuroInterfaceMetricEntry(entry.Label, entry.Value));
        }

        return copy;
    }

    private static List<NeuroInterfaceModuleEntry> CloneModuleEntries(List<NeuroInterfaceModuleEntry> entries)
    {
        var copy = new List<NeuroInterfaceModuleEntry>(entries.Count);
        foreach (var entry in entries)
        {
            copy.Add(new NeuroInterfaceModuleEntry(
                entry.Module,
                entry.SlotId,
                entry.SlotName,
                entry.Name,
                entry.Description));
        }

        return copy;
    }

    private static bool AreAugmentsEqual(List<NeuroInterfaceAugmentEntry> current, List<NeuroInterfaceAugmentEntry>? cached)
    {
        if (cached == null || current.Count != cached.Count)
            return false;

        for (var i = 0; i < current.Count; i++)
        {
            var a = current[i];
            var b = cached[i];
            if (a.Augment != b.Augment
                || a.Part != b.Part
                || a.Category != b.Category
                || a.Name != b.Name
                || a.Enabled != b.Enabled
                || a.CanToggle != b.CanToggle
                || a.CanConfigure != b.CanConfigure
                || a.Status != b.Status
                || a.Description != b.Description
                || !AreMetricListsEqual(a.PassivePowerEntries, b.PassivePowerEntries)
                || !AreMetricListsEqual(a.ActivePowerEntries, b.ActivePowerEntries)
                || !AreMetricListsEqual(a.PassiveNeuroLoadEntries, b.PassiveNeuroLoadEntries)
                || !AreMetricListsEqual(a.ActiveNeuroLoadEntries, b.ActiveNeuroLoadEntries)
                || !AreModuleListsEqual(a.Modules, b.Modules))
            {
                return false;
            }
        }

        return true;
    }

    private static bool AreMetricListsEqual(List<NeuroInterfaceMetricEntry> a, List<NeuroInterfaceMetricEntry> b)
    {
        if (a.Count != b.Count)
            return false;

        for (var i = 0; i < a.Count; i++)
        {
            if (a[i].Label != b[i].Label || MathF.Abs(a[i].Value - b[i].Value) > 0.0001f)
                return false;
        }

        return true;
    }

    private static bool AreModuleListsEqual(List<NeuroInterfaceModuleEntry> a, List<NeuroInterfaceModuleEntry> b)
    {
        if (a.Count != b.Count)
            return false;

        for (var i = 0; i < a.Count; i++)
        {
            if (a[i].Module != b[i].Module
                || a[i].SlotId != b[i].SlotId
                || a[i].SlotName != b[i].SlotName
                || a[i].Name != b[i].Name
                || a[i].Description != b[i].Description)
            {
                return false;
            }
        }

        return true;
    }

    private List<AugmentGroup> BuildAugmentGroups(List<NeuroInterfaceAugmentEntry> entries)
    {
        var partNameCache = new Dictionary<EntityUid, string>(entries.Count);
        var groupsByPart = new Dictionary<NetEntity, AugmentGroup>(entries.Count);
        var groups = new List<AugmentGroup>(entries.Count);

        foreach (var entry in entries)
        {
            if (groupsByPart.TryGetValue(entry.Part, out var existing))
            {
                existing.Entries.Add(entry);
                continue;
            }

            var partUid = _entityManager.GetEntity(entry.Part);
            var group = new AugmentGroup(
                entry.Part,
                entry.Category,
                GetPartNameCached(partUid, partNameCache),
                new List<NeuroInterfaceAugmentEntry> { entry });

            groupsByPart[entry.Part] = group;
            groups.Add(group);
        }

        groups.Sort((a, b) =>
        {
            var categoryCompare = GetCategoryRank(a.Category).CompareTo(GetCategoryRank(b.Category));
            if (categoryCompare != 0)
                return categoryCompare;

            return string.Compare(a.PartName, b.PartName, StringComparison.OrdinalIgnoreCase);
        });

        return groups;
    }

    private static int GetCategoryRank(NeuroInterfaceBodyCategory category)
    {
        return category switch
        {
            NeuroInterfaceBodyCategory.Head => 0,
            NeuroInterfaceBodyCategory.Torso => 1,
            NeuroInterfaceBodyCategory.RightArm => 2,
            NeuroInterfaceBodyCategory.LeftArm => 3,
            NeuroInterfaceBodyCategory.RightHand => 4,
            NeuroInterfaceBodyCategory.LeftHand => 5,
            NeuroInterfaceBodyCategory.Groin => 6,
            NeuroInterfaceBodyCategory.RightLeg => 7,
            NeuroInterfaceBodyCategory.LeftLeg => 8,
            NeuroInterfaceBodyCategory.RightFoot => 9,
            NeuroInterfaceBodyCategory.LeftFoot => 10,
            _ => int.MaxValue,
        };
    }

    private string GetPartNameCached(EntityUid partUid, Dictionary<EntityUid, string> cache)
    {
        if (cache.TryGetValue(partUid, out var cached))
            return cached;

        var value = GetPartName(partUid);
        cache[partUid] = value;
        return value;
    }

    private string GetPartName(EntityUid partUid)
    {
        if (!_entityManager.EntityExists(partUid))
            return Loc.GetString(UnknownPartLocKey);

        if (_entityManager.TryGetComponent<MetaDataComponent>(partUid, out var meta)
            && !string.IsNullOrWhiteSpace(meta.EntityName))
        {
            return meta.EntityName;
        }

        return Loc.GetString(UnknownPartLocKey);
    }

    private Control CreateEntryControl(NeuroInterfaceAugmentEntry entry)
    {
        var hasModules = entry.Modules.Count > 0;
        var augmentCollapsed = hasModules && _viewSettings.CollapsedAugments.Contains(entry.Augment);
        var statusBackground = GetStatusBackground(entry.Status);

        var row = new BoxContainer
        {
            Orientation = LayoutOrientation.Horizontal,
            SeparationOverride = 6,
            HorizontalExpand = true,
        };

        if (hasModules)
        {
            var modulesButton = new Button
            {
                Text = augmentCollapsed ? "v" : "^",
                MinWidth = 24,
                StyleBoxOverride = statusBackground,
            };
            modulesButton.OnPressed += _ =>
            {
                ToggleAugmentCollapsed(entry.Augment);
                if (_cachedAugments != null)
                    RebuildAugments(_cachedAugments);
            };
            row.AddChild(modulesButton);
        }

        var infoButton = new Button
        {
            Text = "?",
            MinWidth = 24,
            StyleBoxOverride = statusBackground,
        };
        infoButton.TooltipSupplier = _ => BuildAugmentTooltip(entry);
        row.AddChild(infoButton);

        row.AddChild(new Label
        {
            Text = entry.Name,
            HorizontalExpand = true,
            Margin = new Thickness(6, 0, 0, 0),
        });

        var toggleButton = new Button
        {
            Text = Loc.GetString(entry.Enabled ? "neuro-interface-button-disable" : "neuro-interface-button-enable"),
            Disabled = !entry.CanToggle,
            MinWidth = 90,
            StyleBoxOverride = statusBackground,
        };

        toggleButton.OnPressed += _ => OnToggleRequested?.Invoke(entry.Augment, !entry.Enabled);
        row.AddChild(toggleButton);

        var settingsButton = new Button
        {
            Text = Loc.GetString("neuro-interface-button-settings"),
            Disabled = !entry.CanConfigure,
            MinWidth = 95,
            StyleBoxOverride = statusBackground,
        };

        row.AddChild(settingsButton);

        var panel = new PanelContainer
        {
            PanelOverride = statusBackground,
            Margin = new Thickness(0, 0, 0, 4),
        };

        panel.AddChild(row);

        if (!hasModules || augmentCollapsed)
            return panel;

        var wrapper = new BoxContainer
        {
            Orientation = LayoutOrientation.Vertical,
            SeparationOverride = 2,
            HorizontalExpand = true,
        };
        wrapper.AddChild(panel);
        wrapper.AddChild(CreateModulesContainer(entry));
        return wrapper;
    }

    private Control CreateModulesContainer(NeuroInterfaceAugmentEntry entry)
    {
        var modules = new BoxContainer
        {
            Orientation = LayoutOrientation.Vertical,
            SeparationOverride = 2,
            Margin = new Thickness(22, 2, 0, 4),
            HorizontalExpand = true,
        };

        foreach (var module in entry.Modules)
        {
            var row = new PanelContainer
            {
                PanelOverride = GetStatusBackground(entry.Status),
                Margin = new Thickness(0, 0, 0, 2),
            };

            var description = string.IsNullOrWhiteSpace(module.Description)
                ? Loc.GetString(UnknownDescriptionLocKey)
                : module.Description;

            var line = new Label
            {
                Text = Loc.GetString("neuro-interface-module-line",
                    ("slot", module.SlotName),
                    ("name", module.Name)),
                Margin = new Thickness(6, 3, 6, 3),
                HorizontalExpand = true,
            };
            line.ToolTip = description;
            row.AddChild(line);
            modules.AddChild(row);
        }

        return modules;
    }

    private Control BuildAugmentTooltip(NeuroInterfaceAugmentEntry entry)
    {
        var description = string.IsNullOrWhiteSpace(entry.Description)
            ? Loc.GetString(UnknownDescriptionLocKey)
            : entry.Description;

        var root = new BoxContainer
        {
            Orientation = LayoutOrientation.Vertical,
            SeparationOverride = 4,
            Margin = new Thickness(8),
        };

        AddTooltipText(root, Loc.GetString(GetStatusTooltipLocKey(entry.Status)));
        AddTooltipText(root, Loc.GetString("neuro-interface-tooltip-description", ("description", description)));
        if (entry.Modules.Count > 0)
        {
            AddTooltipText(root, Loc.GetString("neuro-interface-modules-label"), new Thickness(0, 2, 0, 0));
            foreach (var module in entry.Modules)
            {
                AddTooltipText(root, Loc.GetString("neuro-interface-module-line",
                    ("slot", module.SlotName),
                    ("name", module.Name)), new Thickness(8, 0, 0, 0));
            }
        }

        AddMetricSection(root, "neuro-interface-tooltip-section-power-passive", entry.PassivePowerEntries);
        AddMetricSection(root, "neuro-interface-tooltip-section-power-active", entry.ActivePowerEntries);
        AddMetricSection(root, "neuro-interface-tooltip-section-neuro-passive", entry.PassiveNeuroLoadEntries);
        AddMetricSection(root, "neuro-interface-tooltip-section-neuro-active", entry.ActiveNeuroLoadEntries);

        var panel = new PanelContainer
        {
            PanelOverride = GetTooltipBackground(entry.Status),
        };
        panel.AddChild(root);
        return panel;
    }

    private static void AddMetricSection(BoxContainer parent, string titleKey, List<NeuroInterfaceMetricEntry> entries)
    {
        if (entries.Count == 0)
            return;

        AddTooltipText(parent, Loc.GetString(titleKey), new Thickness(0, 2, 0, 0));

        foreach (var entry in entries)
        {
            var label = entry.Label.StartsWith("neuro-interface-", StringComparison.Ordinal)
                ? Loc.GetString(entry.Label)
                : entry.Label;

            AddTooltipText(parent, Loc.GetString("neuro-interface-tooltip-metric-line",
                ("label", label),
                ("value", entry.Value.ToString("0.0"))), new Thickness(8, 0, 0, 0));
        }
    }

    private static void AddTooltipText(BoxContainer parent, string text, Thickness? margin = null)
    {
        var line = new RichTextLabel
        {
            MaxWidth = TooltipTextMaxWidth,
            HorizontalExpand = true,
            Margin = margin ?? new Thickness(0),
        };
        line.SetMessage(FormattedMessage.FromUnformatted(text), defaultColor: Color.White);
        parent.AddChild(line);
    }

    private static string GetGroupHeaderText(string partName, bool collapsed)
    {
        var arrow = collapsed ? "v" : "^";
        return OopsConcat(OopsConcat(arrow, " | "), CapitalizeFirstSafe(partName));
    }

    private static string CapitalizeFirstSafe(string text)
    {
        if (string.IsNullOrEmpty(text))
            return text;

        return OopsConcat(char.ToUpper(text[0]).ToString(), text.Remove(0, 1));
    }

    private static string OopsConcat(string a, string b)
    {
        return a + b;
    }

    private void ToggleGroupCollapsed(NetEntity part)
    {
        if (!_viewSettings.CollapsedGroups.Remove(part))
            _viewSettings.CollapsedGroups.Add(part);
    }

    private void ToggleAugmentCollapsed(NetEntity augment)
    {
        if (!_viewSettings.CollapsedAugments.Remove(augment))
            _viewSettings.CollapsedAugments.Add(augment);
    }

    private static StyleBoxFlat GetStatusBackground(NeuroInterfaceAugmentStatus status)
    {
        return status switch
        {
            NeuroInterfaceAugmentStatus.Enabled => EnabledBackground,
            NeuroInterfaceAugmentStatus.Disabled => DisabledBackground,
            NeuroInterfaceAugmentStatus.Deactivated => DeactivatedBackground,
            NeuroInterfaceAugmentStatus.NoPower => NoPowerBackground,
            _ => DisabledBackground,
        };
    }

    private static StyleBoxFlat GetTooltipBackground(NeuroInterfaceAugmentStatus status)
    {
        return status switch
        {
            NeuroInterfaceAugmentStatus.Enabled => EnabledTooltipBackground,
            NeuroInterfaceAugmentStatus.Disabled => DisabledTooltipBackground,
            NeuroInterfaceAugmentStatus.Deactivated => DeactivatedTooltipBackground,
            NeuroInterfaceAugmentStatus.NoPower => NoPowerTooltipBackground,
            _ => DisabledTooltipBackground,
        };
    }

    private static string GetStatusTooltipLocKey(NeuroInterfaceAugmentStatus status)
    {
        return status switch
        {
            NeuroInterfaceAugmentStatus.Enabled => "neuro-interface-status-tooltip-enabled",
            NeuroInterfaceAugmentStatus.Disabled => "neuro-interface-status-tooltip-disabled",
            NeuroInterfaceAugmentStatus.Deactivated => "neuro-interface-status-tooltip-deactivated",
            NeuroInterfaceAugmentStatus.NoPower => "neuro-interface-status-tooltip-no-power",
            _ => "neuro-interface-status-tooltip-disabled",
        };
    }

}
