- type: entity
  abstract: true
  parent: BaseAugment
  id: BaseOnyxAugment
  description: Augment
  components:
  - type: Item
    size: Huge
  - type: AugmentExamine
    visible: true
  - type: AugmentEmp
  - type: AugmentPowerConfig
  - type: Tag
    tags:
    - Augment

- type: entity
  abstract: true
  parent: BaseOnyxAugment
  id: BaseOnyxLegAugment
  description: Augment
  components:
  - type: Sprite
    sprite: _Shitmed/Objects/Augments/power.rsi
    state: cell
  - type: Organ
    slotId: legImplant
    toolName: surgery-tool-augment-target-leg
  - type: Tag
    tags:
    - LegAugment
    - Augment

- type: entity
  abstract: true
  parent: BaseOnyxAugment
  id: BaseOnyxFootAugment
  description: Augment
  components:
  - type: Sprite
    sprite: _Shitmed/Objects/Augments/power.rsi
    state: cell
  - type: Organ
    slotId: footImplant
    toolName: surgery-tool-augment-target-foot
  - type: Tag
    tags:
    - footAugment
    - Augment

- type: entity
  abstract: true
  parent: BaseOnyxAugment
  id: BaseOnyxChestAugment
  description: Augment
  components:
  - type: Sprite
    sprite: _Shitmed/Objects/Augments/power.rsi
    state: cell
  - type: Organ
    slotId: chestImplant
    toolName: surgery-tool-augment-target-chest
  - type: Tag
    tags:
    - chestAugment
    - Augment

- type: entity
  abstract: true
  parent: BaseOnyxAugment
  id: BaseOnyxHeadAugment
  description: Augment
  components:
  - type: Sprite
    sprite: _Shitmed/Objects/Augments/power.rsi
    state: cell
  - type: Organ
    slotId: headImplant
    toolName: surgery-tool-augment-target-head
  - type: Tag
    tags:
    - headAugment
    - Augment

- type: entity
  abstract: true
  parent: BaseOnyxAugment
  id: BaseOnyxEyeAugment
  description: Augment
  components:
  - type: Sprite
    sprite: _Shitmed/Objects/Augments/power.rsi
    state: cell
  - type: Organ
    slotId: eyeImplant
    toolName: surgery-tool-augment-target-eye
  - type: Tag
    tags:
    - eyeAugment
    - Augment

- type: entity
  abstract: true
  parent: BaseOnyxAugment
  id: BaseOnyxBrainAugment
  description: Augment
  components:
  - type: Sprite
    sprite: _Shitmed/Objects/Augments/power.rsi
    state: cell
  - type: Organ
    slotId: brainImplant
    toolName: surgery-tool-augment-target-brain
  - type: Tag
    tags:
    - brainAugment
    - Augment

- type: entity
  abstract: true
  parent: BaseOnyxAugment
  id: BaseOnyxArmAugment
  description: Augment
  components:
  - type: Sprite
    sprite: _Shitmed/Objects/Augments/power.rsi
    state: cell
  - type: Organ
    slotId: armImplant
    toolName: surgery-tool-augment-target-arm
  - type: Tag
    tags:
    - armAugment
    - Augment

- type: entity
  abstract: true
  parent: BaseOnyxAugment
  id: BaseOnyxHandAugment
  description: Augment
  components:
  - type: Sprite
    sprite: _Shitmed/Objects/Augments/power.rsi
    state: cell
  - type: Organ
    slotId: handImplant
    toolName: surgery-tool-augment-target-hand
  - type: Tag
    tags:
    - handAugment
    - Augment

- type: entity
  abstract: true
  parent: BaseOnyxAugment
  id: BaseOnyxNeckAugment
  description: Augment
  components:
  - type: Sprite
    sprite: _Shitmed/Objects/Augments/power.rsi
    state: cell
  - type: Organ
    slotId: neckImplant
    toolName: surgery-tool-augment-target-neck
  - type: Tag
    tags:
    - neckAugment
    - Augment
