using System.Text.RegularExpressions;
using Content.Shared._Onyx.Economy;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Timing;
using FancyWindow = Content.Client.UserInterface.Controls.FancyWindow;

namespace Content.Client._Onyx.Economy.UI;

[GenerateTypedNameReferences]
public sealed partial class AtmWindow : FancyWindow
{
    public Action<ATMRequestWithdrawMessage>? OnWithdrawAttempt;
    public Action<ATMPinVerifyMessage>? OnPinVerifyAttempt;

    private readonly string _pinPattern = "[^0-9]";
    private int _currentBalance;

    public AtmWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        PinEntryNextButton.OnButtonDown += _ =>
        {
            if (PinEntryLineEdit.Text.Length != 4) return;
            OnPinVerifyAttempt?.Invoke(new ATMPinVerifyMessage(int.Parse(PinEntryLineEdit.Text)));
        };

        PinEntryLineEdit.OnTextChanged += _ =>
        {
            ValidatePinEntry();
        };

        Withdraw10Button.OnButtonDown += _ =>
        {
            AttemptWithdraw(10);
        };

        Withdraw50Button.OnButtonDown += _ =>
        {
            AttemptWithdraw(50);
        };

        Withdraw100Button.OnButtonDown += _ =>
        {
            AttemptWithdraw(100);
        };

        Withdraw500Button.OnButtonDown += _ =>
        {
            AttemptWithdraw(500);
        };

        CustomWithdrawButton.OnButtonDown += _ =>
        {
            if (int.TryParse(CustomAmountLineEdit.Text, out var amount) && amount > 0)
            {
                AttemptWithdraw(amount);
            }
        };

        CustomAmountLineEdit.OnTextChanged += _ =>
        {
            ValidateCustomAmount();
        };

        NoCardHeaderLabel.Text = Loc.GetString("atm-ui-bank-header");
        NoCardMessageLabel.Text = Loc.GetString("atm-ui-insert-card");
        PinEntryHeaderLabel.Text = Loc.GetString("atm-ui-bank-header");
        PinEntryTitleLabel.Text = Loc.GetString("atm-ui-enter-pin-title");
        MainHeaderLabel.Text = Loc.GetString("atm-ui-bank-header");
        WithdrawTitleLabel.Text = Loc.GetString("atm-ui-withdraw-title");
        BalanceTitleLabel.Text = Loc.GetString("atm-ui-balance-title");
    }

    private void AttemptWithdraw(int amount)
    {
        if (amount > _currentBalance) return;
        OnWithdrawAttempt?.Invoke(new ATMRequestWithdrawMessage(amount, 0));
    }

    public void UpdateState(BoundUserInterfaceState state)
    {
        if(state is not ATMBuiState cast) return;

        _currentBalance = cast.AccountBalance;

        NoCardPage.Visible = false;
        PinEntryPage.Visible = false;
        MainPage.Visible = false;

        switch (cast.CurrentState)
        {
            case ATMUiState.NoCard:
                NoCardPage.Visible = true;
                break;

            case ATMUiState.PinEntry:
                PinEntryPage.Visible = true;
                PinEntryLineEdit.Text = string.Empty;
                break;

            case ATMUiState.MainMenu:
                MainPage.Visible = true;
                WelcomeLabel.Text = Loc.GetString("atm-ui-welcome", ("owner", cast.OwnerName));
                BalanceValueLabel.Text = $" {_currentBalance}$";
                BalanceValueLabel.FontColorOverride = Color.Lime;

                Withdraw10Button.Disabled = _currentBalance < 10;
                Withdraw50Button.Disabled = _currentBalance < 50;
                Withdraw100Button.Disabled = _currentBalance < 100;
                Withdraw500Button.Disabled = _currentBalance < 500;
                break;
        }
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);

        if (PinEntryPage.Visible)
        {
            PinEntryNextButton.Disabled = PinEntryLineEdit.Text.Length != 4;
        }

        if (MainPage.Visible)
        {
            CustomWithdrawButton.Disabled = !int.TryParse(CustomAmountLineEdit.Text, out var amount) || amount <= 0 || amount > _currentBalance;
        }
    }

    private void ValidatePinEntry()
    {
        var pinText = Regex.Replace(PinEntryLineEdit.Text, _pinPattern, string.Empty);

        if (pinText.Length > 4)
        {
            pinText = pinText[..4];
        }

        PinEntryLineEdit.Text = pinText;
    }

    private void ValidateCustomAmount()
    {
        var amountText = Regex.Replace(CustomAmountLineEdit.Text, _pinPattern, string.Empty);
        if (amountText.Length > 8)
        {
            amountText = amountText[..8];
        }

        CustomAmountLineEdit.Text = amountText;
    }
}
