// SPDX-FileCopyrightText: 2021 DrSmugleaf <DrSmugleaf@users.noreply.github.com>
// SPDX-FileCopyrightText: 2021 Visne <39844191+Visne@users.noreply.github.com>
// SPDX-FileCopyrightText: 2022 Jesse Rougeau <jmaster9999@gmail.com>
// SPDX-FileCopyrightText: 2022 ZeroDayDaemon <60460608+ZeroDayDaemon@users.noreply.github.com>
// SPDX-FileCopyrightText: 2022 mirrorcult <lunarautomaton6@gmail.com>
// SPDX-FileCopyrightText: 2023 Flipp Syder <76629141+vulppine@users.noreply.github.com>
// SPDX-FileCopyrightText: 2024 12rabbits <53499656+12rabbits@users.noreply.github.com>
// SPDX-FileCopyrightText: 2024 Alzore <140123969+Blackern5000@users.noreply.github.com>
// SPDX-FileCopyrightText: 2024 ArtisticRoomba <145879011+ArtisticRoomba@users.noreply.github.com>
// SPDX-FileCopyrightText: 2024 Brandon Hu <103440971+Brandon-Huu@users.noreply.github.com>
// SPDX-FileCopyrightText: 2024 Dimastra <65184747+Dimastra@users.noreply.github.com>
// SPDX-FileCopyrightText: 2024 Dimastra <dimastra@users.noreply.github.com>
// SPDX-FileCopyrightText: 2024 Ed <96445749+TheShuEd@users.noreply.github.com>
// SPDX-FileCopyrightText: 2024 Emisse <99158783+Emisse@users.noreply.github.com>
// SPDX-FileCopyrightText: 2024 Eoin Mcloughlin <helloworld@eoinrul.es>
// SPDX-FileCopyrightText: 2024 Fildrance <fildrance@gmail.com>
// SPDX-FileCopyrightText: 2024 Firewatch <54725557+musicmanvr@users.noreply.github.com>
// SPDX-FileCopyrightText: 2024 IProduceWidgets <107586145+IProduceWidgets@users.noreply.github.com>
// SPDX-FileCopyrightText: 2024 JIPDawg <51352440+JIPDawg@users.noreply.github.com>
// SPDX-FileCopyrightText: 2024 JIPDawg <JIPDawg93@gmail.com>
// SPDX-FileCopyrightText: 2024 Mervill <mervills.email@gmail.com>
// SPDX-FileCopyrightText: 2024 Moomoobeef <62638182+Moomoobeef@users.noreply.github.com>
// SPDX-FileCopyrightText: 2024 Mr. 27 <45323883+Dutch-VanDerLinde@users.noreply.github.com>
// SPDX-FileCopyrightText: 2024 Mr. 27 <koolthunder019@gmail.com>
// SPDX-FileCopyrightText: 2024 Nemanja <98561806+EmoGarbage404@users.noreply.github.com>
// SPDX-FileCopyrightText: 2024 PJBot <pieterjan.briers+bot@gmail.com>
// SPDX-FileCopyrightText: 2024 Pieter-Jan Briers <pieterjan.briers+git@gmail.com>
// SPDX-FileCopyrightText: 2024 Pieter-Jan Briers <pieterjan.briers@gmail.com>
// SPDX-FileCopyrightText: 2024 PopGamer46 <yt1popgamer@gmail.com>
// SPDX-FileCopyrightText: 2024 PursuitInAshes <pursuitinashes@gmail.com>
// SPDX-FileCopyrightText: 2024 QueerNB <176353696+QueerNB@users.noreply.github.com>
// SPDX-FileCopyrightText: 2024 Saphire Lattice <lattice@saphi.re>
// SPDX-FileCopyrightText: 2024 ShadowCommander <10494922+ShadowCommander@users.noreply.github.com>
// SPDX-FileCopyrightText: 2024 Simon <63975668+Simyon264@users.noreply.github.com>
// SPDX-FileCopyrightText: 2024 Spessmann <156740760+Spessmann@users.noreply.github.com>
// SPDX-FileCopyrightText: 2024 Thomas <87614336+Aeshus@users.noreply.github.com>
// SPDX-FileCopyrightText: 2024 Winkarst <74284083+Winkarst-cpu@users.noreply.github.com>
// SPDX-FileCopyrightText: 2024 deltanedas <39013340+deltanedas@users.noreply.github.com>
// SPDX-FileCopyrightText: 2024 deltanedas <@deltanedas:kde.org>
// SPDX-FileCopyrightText: 2024 dffdff2423 <dffdff2423@gmail.com>
// SPDX-FileCopyrightText: 2024 eoineoineoin <github@eoinrul.es>
// SPDX-FileCopyrightText: 2024 github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
// SPDX-FileCopyrightText: 2024 lzk <124214523+lzk228@users.noreply.github.com>
// SPDX-FileCopyrightText: 2024 metalgearsloth <31366439+metalgearsloth@users.noreply.github.com>
// SPDX-FileCopyrightText: 2024 pa.pecherskij <pa.pecherskij@interfax.ru>
// SPDX-FileCopyrightText: 2024 slarticodefast <161409025+slarticodefast@users.noreply.github.com>
// SPDX-FileCopyrightText: 2024 stellar-novas <stellar_novas@riseup.net>
// SPDX-FileCopyrightText: 2024 themias <89101928+themias@users.noreply.github.com>
// SPDX-FileCopyrightText: 2025 Aiden <28298836+Aidenkrz@users.noreply.github.com>
// SPDX-FileCopyrightText: 2025 Piras314 <p1r4s@proton.me>
//
// SPDX-License-Identifier: AGPL-3.0-or-later

using System;
using Content.Client.Administration.UI.CustomControls;
using Content.Client._Onyx.Discord;
using Content.Client.Info;
using Content.Client.Message;
using Content.Client.UserInterface.Systems.EscapeMenu;
using Content.Corvax.Interfaces.Client;
using Content.Shared.CCVar;
using Robust.Client.Console;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Configuration;
using Robust.Shared.Network;
using Robust.Client.AutoGenerated;
using Robust.Shared.Timing;

namespace Content.Client.Lobby.UI
{
    [GenerateTypedNameReferences]
    public sealed partial class LobbyGui : UIScreen
    {
        [Dependency] private readonly IClientConsoleHost _consoleHost = default!;
        [Dependency] private readonly DiscordIdManager _discordIdManager = default!;
        [Dependency] private readonly IConfigurationManager _cfg = default!;
        [Dependency] private readonly IClientNetManager _netMgr = default!;
        private float _updateTimer;
        // <Onyx-DiscordAuth>
        private DiscordLinkWindow? _forcedDiscordWindow;
        private static readonly Color ColorBlue = Color.FromHex("#1966ff");   // Синий
        private static readonly Color ColorRed = Color.FromHex("#AB3232"); // Красный

        private static readonly Color ColorGreen = Color.FromHex("#5DA130");   // Зелёный
        private static readonly Color ColorOrange = Color.FromHex("#FFA500");  // Оранжевый
        // </Onyx-DiscordAuth>

        public LobbyGui()
        {
            RobustXamlLoader.Load(this);
            IoCManager.InjectDependencies(this);
            SetAnchorPreset(MainContainer, LayoutPreset.Wide);
            SetAnchorPreset(Background, LayoutPreset.Wide);

            LobbySong.SetMarkup(Loc.GetString("lobby-state-song-no-song-text"));
            LobbyBackground.SetMarkup(Loc.GetString("lobby-state-background-no-background-text")); // Goobstation

            LeaveButton.OnPressed += _ => _consoleHost.ExecuteCommand("disconnect");
            OptionsButton.OnPressed += _ => UserInterfaceManager.GetUIController<OptionsUIController>().ToggleWindow();

            CollapseButton.OnPressed += _ => TogglePanel(false);
            ExpandButton.OnPressed += _ => TogglePanel(true);
            // <Onyx-Lobby>
            LeftCollapseButton.OnPressed += _ => ToggleLeftPanel(false);
            LeftExpandButton.OnPressed += _ => ToggleLeftPanel(true);

            TopCollapseButton.OnPressed += _ => ToggleTopPanel(false);
            TopExpandButton.OnPressed += _ => ToggleTopPanel(true);

            AttributionCollapseButton.OnPressed += _ => ToggleAttributionPanel(false);
            AttributionExpandButton.OnPressed += _ => ToggleAttributionPanel(true);
            // </Onyx-Lobby>
            _discordIdManager.DiscordInfoUpdated += OnDiscordInfoUpdated;
            _netMgr.Disconnect += OnNetDisconnected;
            _discordIdManager.RequestDiscordInfo();

            UpdateDiscordButtonState(); // </Onyx-Lobby>
            EnsureMandatoryDiscordLinkWindow();
        }

        public void SwitchState(LobbyGuiState state)
        {
            DefaultState.Visible = false;
            CharacterSetupState.Visible = false;

            switch (state)
            {
                case LobbyGuiState.Default:
                    DefaultState.Visible = true;
                    RightSide.Visible = true;
                    // <Onyx-Lobby>
                    LeftSide.HorizontalExpand = false;
                    LayoutSpacer.Visible = true;
                    ExpandPanel.Visible = false;
                    TopPanel.Visible = true;
                    TopExpandPanel.Visible = false;
                    LeftInfoPanel.Visible = true;
                    LeftExpandPanel.Visible = false;
                    AttributionPanel.Visible = false;
                    AttributionExpandPanel.Visible = true;

                    UpdateDiscordButtonState();
                    // </Onyx-Lobby>
                    break;
                case LobbyGuiState.CharacterSetup:
                    CharacterSetupState.Visible = true;

                    // <Onyx-Lobby>
                    LeftSide.HorizontalExpand = true;
                    LayoutSpacer.Visible = false;
                    RightSide.Visible = false;
                    // </Onyx-Lobby>

                    UserInterfaceManager.GetUIController<LobbyUIController>().ReloadCharacterSetup();
                    break;
            }
        }
        protected override void FrameUpdate(FrameEventArgs args)
        {
            base.FrameUpdate(args);

            var requiresDiscordRefresh = ShouldShowDiscordButton() ||
                                         _cfg.GetCVar(CCVars.DiscordAuthLinkRequired) ||
                                         (_forcedDiscordWindow?.IsOpen ?? false); // <Onyx-Lobby>

            if (!requiresDiscordRefresh)
                return;

            _updateTimer += args.DeltaSeconds;
            if (_updateTimer > 5.0f)
            {
                _updateTimer = 0;
                _discordIdManager.RequestDiscordInfo();
                UpdateDiscordButtonState(); // <Onyx-Lobby>
            }

            EnsureMandatoryDiscordLinkWindow();
        }

        // <Onyx-Lobby>
        private bool ShouldShowDiscordButton()
        {
            return _cfg.GetCVar(CCVars.ExtraLobbyPanelEnabled);
        }

        private void OnDiscordInfoUpdated()
        {
            UpdateDiscordButtonState();
            EnsureMandatoryDiscordLinkWindow();
        }

        private void UpdateDiscordButtonState()
        {
            if (DiscordLinkButton == null)
                return;

            DiscordLinkButton.Visible = ShouldShowDiscordButton();
            if (!DiscordLinkButton.Visible)
                return;

            UpdateDiscordLinkButtonColor(_discordIdManager?.TryGetDiscordId(out _));
        }

        private void EnsureMandatoryDiscordLinkWindow()
        {
            if (!_netMgr.IsConnected ||
                !_cfg.GetCVar(CCVars.DiscordAuthLinkRequired) ||
                _discordIdManager.TryGetDiscordId(out _))
            {
                CloseMandatoryDiscordLinkWindow();
                return;
            }

            if (_forcedDiscordWindow == null || _forcedDiscordWindow.Disposed)
            {
                _forcedDiscordWindow = new DiscordLinkWindow();
                _forcedDiscordWindow.SetForcedMode(true);
            }

            if (!_forcedDiscordWindow.IsOpen)
            {
                _forcedDiscordWindow.OpenCentered();
            }
            else
            {
                _forcedDiscordWindow.MoveToFront();
            }
        }

        private void CloseMandatoryDiscordLinkWindow()
        {
            if (_forcedDiscordWindow == null)
                return;

            if (_forcedDiscordWindow.IsOpen)
                _forcedDiscordWindow.ForceClose();

            _forcedDiscordWindow.Dispose();
            _forcedDiscordWindow = null;
        }

        private void OnNetDisconnected(object? sender, NetDisconnectedArgs args)
        {
            CloseMandatoryDiscordLinkWindow();
        }
        public void UpdateDiscordLinkButtonColor(bool? isLinked)
        {
            if (DiscordLinkButton == null)
                return;

            var (color, text) = isLinked switch
            {
                true  => (ColorGreen, Loc.GetString("ui-lobby-discord-menu-link")),    // Зелёный
                false => (ColorRed, Loc.GetString("ui-lobby-discord-menu-make-link")), // Красный
                null  => (ColorOrange, Loc.GetString("ui-lobby-discord-menu-error"))   // Оранжевый
            };

            DiscordLinkButton.ModulateSelfOverride = color;
            DiscordLinkButton.Text = text;
        }
        // </Onyx-DiscordAuth>

        private void TogglePanel(bool value)
        {
            RightSide.Visible = value;
            ExpandPanel.Visible = !value;
        }
        // <Onyx-Lobby>
        private void ToggleLeftPanel(bool value)
        {
            LeftInfoPanel.Visible = value;
            LeftExpandPanel.Visible = !value;
        }

        private void ToggleTopPanel(bool value)
        {
            TopPanel.Visible = value;
            TopExpandPanel.Visible = !value;
        }

        private void ToggleAttributionPanel(bool value)
        {
            AttributionPanel.Visible = value;
            AttributionExpandPanel.Visible = !value;
        }
        // </Onyx-Lobby>

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                _discordIdManager.DiscordInfoUpdated -= OnDiscordInfoUpdated;
                _netMgr.Disconnect -= OnNetDisconnected; // <Onyx-DiscordAuth>
                CloseMandatoryDiscordLinkWindow(); // <Onyx-DiscordAuth>
            }
            base.Dispose(disposing);
        }

        public enum LobbyGuiState : byte
        {
            /// <summary>
            ///  The default state, i.e., what's seen on launch.
            /// </summary>
            Default,
            /// <summary>
            ///  The character setup state.
            /// </summary>
            CharacterSetup
        }
    }
}
