using Content.Client.UserInterface.Controls;
using Content.Client.UserInterface.Controls.FancyTree;
using Content.Client._Onyx.Wiki;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Client.WebView;
using System.Linq;

namespace Content.Client._Onyx.Wiki.UI;

[GenerateTypedNameReferences]
public sealed partial class WikiWindow : FancyWindow
{
    private readonly WebViewControl _webView;
    private readonly WikiManager _wiki;
    private string? _selectedArticleId;
    private int _articleSearchHit;
    private int _articleSearchMatches;
    private bool _updatingTreeSelection;

    public string? SelectedArticleId => _selectedArticleId;

    public WikiWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _wiki = IoCManager.Resolve<WikiManager>();
        _webView = new WebViewControl
        {
            HorizontalExpand = true,
            VerticalExpand = true
        };

        _webView.AddResourceRequestHandler(_wiki.HandleResourceRequest);
        _webView.AddBeforeBrowseHandler(HandleBeforeBrowse);
        WebPanel.AddChild(_webView);

        SearchBar.OnTextChanged += _ => RebuildResults(SearchBar.Text);
        ArticleSearchBar.OnTextChanged += _ =>
        {
            _articleSearchHit = 0;
            ApplyArticleSearch();
        };
        ArticleSearchBar.OnTextEntered += _ => SelectNextArticleSearchHit();
        ArticleTree.OnSelectedItemChanged += item =>
        {
            if (_updatingTreeSelection)
                return;

            if (item?.Metadata is string id)
                OpenArticle(id);
        };

        BackButton.OnPressed += _ => _webView.GoBack();
        ForwardButton.OnPressed += _ => _webView.GoForward();
        ReloadButton.OnPressed += _ => _webView.Reload();

        RebuildResults(string.Empty);
    }

    protected override void Dispose(bool disposing)
    {
        _webView.RemoveResourceRequestHandler(_wiki.HandleResourceRequest);
        _webView.RemoveBeforeBrowseHandler(HandleBeforeBrowse);
        _webView.Url = "about:blank";
        base.Dispose(disposing);
    }

    public void OpenDefault()
    {
        if (_wiki.GetDefaultArticle() is { } article)
            OpenArticle(article.Id);
    }

    public void OpenArticle(string id)
    {
        if (!_wiki.TryGetArticle(id, out var article))
            return;

        _selectedArticleId = article.Id;
        _articleSearchHit = 0;
        ArticleTitle.Text = article.Title;
        _articleSearchMatches = _wiki.CountArticleSearchMatches(_selectedArticleId, ArticleSearchBar.Text);
        UpdateArticleSearchCount();
        LoadSelectedArticle();
        SelectResult(article.Id);
    }

    private void RebuildResults(string query)
    {
        var selected = _selectedArticleId;
        ArticleTree.Clear();

        if (query.Trim().Length == 0)
            RebuildArticleTree();
        else
            RebuildSearchTree(query);

        ArticleTree.SetAllExpanded(query.Trim().Length != 0, query.Trim().Length == 0 ? 1 : -1);

        if (selected != null)
            SelectResult(selected);
    }

    private void RebuildSearchTree(string query)
    {
        string? category = null;
        TreeItem? header = null;
        foreach (var article in _wiki.Search(query))
        {
            if (!article.Category.Equals(category, StringComparison.CurrentCultureIgnoreCase))
            {
                category = article.Category;
                header = ArticleTree.AddItem();
                header.Label.Text = category;
            }

            var item = ArticleTree.AddItem(header);
            item.Label.Text = article.Title;
            item.Metadata = article.Id;
        }
    }

    private void RebuildArticleTree()
    {
        var articles = _wiki.Search(string.Empty).ToArray();
        var articleIds = articles
            .Select(x => x.Id.ToLowerInvariant())
            .ToHashSet();

        var children = articles
            .Where(x => !string.IsNullOrWhiteSpace(x.ParentId))
            .GroupBy(x => x.ParentId!.ToLowerInvariant())
            .ToDictionary(x => x.Key, x => x.ToList());

        var added = new HashSet<string>();
        var categoryItems = new Dictionary<string, TreeItem>();

        foreach (var article in articles)
        {
            if (!string.IsNullOrWhiteSpace(article.ParentId)
                && articleIds.Contains(article.ParentId.ToLowerInvariant()))
                continue;

            var categoryItem = GetOrCreateCategoryItem(article.Category, categoryItems);
            AddArticleTreeItem(article, categoryItem, children, added, 0);
        }

        foreach (var article in articles)
        {
            var id = article.Id.ToLowerInvariant();
            if (added.Contains(id))
                continue;

            categoryItems.TryGetValue(article.Category.ToLowerInvariant(), out var parent);
            AddArticleTreeItem(article, parent, children, added, 0);
        }
    }

    private TreeItem GetOrCreateCategoryItem(string category, Dictionary<string, TreeItem> categoryItems)
    {
        var id = category.ToLowerInvariant();
        if (categoryItems.TryGetValue(id, out var item))
            return item;

        item = ArticleTree.AddItem();
        item.Label.Text = category;
        categoryItems[id] = item;
        return item;
    }

    private void AddArticleTreeItem(
        WikiArticleDocument article,
        TreeItem? parent,
        Dictionary<string, List<WikiArticleDocument>> children,
        HashSet<string> added,
        int depth)
    {
        var id = article.Id.ToLowerInvariant();
        if (!added.Add(id))
            return;

        var item = ArticleTree.AddItem(parent);
        item.Label.Text = article.Title;
        item.Metadata = article.Id;

        if (depth >= WikiManager.MaxArticleTreeDepth || !children.TryGetValue(id, out var childArticles))
            return;

        foreach (var child in childArticles
                     .OrderBy(x => x.Prototype.Priority)
                     .ThenBy(x => x.Title.ToLowerInvariant()))
        {
            AddArticleTreeItem(child, item, children, added, depth + 1);
        }
    }

    private void SelectResult(string id)
    {
        var normalizedId = id.ToLowerInvariant();
        for (var i = 0; i < ArticleTree.Items.Count; i++)
        {
            var item = ArticleTree.Items[i];
            if (item.Metadata is not string itemId || itemId.ToLowerInvariant() != normalizedId)
                continue;

            _updatingTreeSelection = true;
            ArticleTree.ExpandParentEntries(i);
            ArticleTree.SetSelectedIndex(i);
            _updatingTreeSelection = false;
            return;
        }
    }

    private void ApplyArticleSearch()
    {
        if (_selectedArticleId == null)
            return;

        _articleSearchMatches = _wiki.CountArticleSearchMatches(_selectedArticleId, ArticleSearchBar.Text);
        if (_articleSearchMatches == 0)
            _articleSearchHit = 0;
        else if (_articleSearchHit >= _articleSearchMatches)
            _articleSearchHit = _articleSearchMatches - 1;

        UpdateArticleSearchCount();
        LoadSelectedArticle();
    }

    private void SelectNextArticleSearchHit()
    {
        if (_selectedArticleId == null)
            return;

        _articleSearchMatches = _wiki.CountArticleSearchMatches(_selectedArticleId, ArticleSearchBar.Text);
        if (_articleSearchMatches > 0)
            _articleSearchHit = (_articleSearchHit + 1) % _articleSearchMatches;

        UpdateArticleSearchCount();
        LoadSelectedArticle();
    }

    private void LoadSelectedArticle()
    {
        if (_selectedArticleId == null)
            return;

        var generation = _wiki.SetArticleSearch(_selectedArticleId, ArticleSearchBar.Text, _articleSearchHit);
        var anchor = _articleSearchMatches > 0 ? $"#wiki-search-hit-{_articleSearchHit}" : string.Empty;
        _webView.Url = $"{_wiki.GetArticleUri(_selectedArticleId)}?s={generation}{anchor}";
    }

    private void HandleBeforeBrowse(IBeforeBrowseContext context)
    {
        if (!_wiki.TryGetArticleIdFromUrl(context.Url, out var articleId))
        {
            context.DoCancel();
            return;
        }

        if (!_wiki.TryGetArticle(articleId, out var article))
            return;

        _selectedArticleId = article.Id;
        _articleSearchHit = 0;
        ArticleTitle.Text = article.Title;
        _articleSearchMatches = _wiki.CountArticleSearchMatches(_selectedArticleId, ArticleSearchBar.Text);
        UpdateArticleSearchCount();
        SelectResult(article.Id);
    }

    private void UpdateArticleSearchCount()
    {
        ArticleSearchCount.Text = _articleSearchMatches == 0
            ? string.Empty
            : $"{_articleSearchHit + 1}/{_articleSearchMatches}";
    }
}
