// SPDX-FileCopyrightText: 2023 chromiumboy <50505512+chromiumboy@users.noreply.github.com>
// SPDX-FileCopyrightText: 2024 Nemanja <98561806+EmoGarbage404@users.noreply.github.com>
// SPDX-FileCopyrightText: 2024 TGRCDev <tgrc@tgrc.dev>
// SPDX-FileCopyrightText: 2024 iacore <74560659+iacore@users.noreply.github.com>
// SPDX-FileCopyrightText: 2024 iacore <noreply+gpg-stub@1a-insec.net>
// SPDX-FileCopyrightText: 2024 metalgearsloth <31366439+metalgearsloth@users.noreply.github.com>
// SPDX-FileCopyrightText: 2025 Aiden <28298836+Aidenkrz@users.noreply.github.com>
//
// SPDX-License-Identifier: AGPL-3.0-or-later

using System.Numerics;
using Content.Client.UserInterface.Controls;
using Content.Shared._CE.ZLevels.Core.EntitySystems;
using Content.Shared._Onyx.UI;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Map;
using Content.Shared.Pinpointer;

namespace Content.Client.Pinpointer.UI;

[GenerateTypedNameReferences]
public sealed partial class StationMapWindow : FancyWindow
{
    [Dependency] private readonly IEntityManager _entMan = default!;
    private readonly CESharedZLevelsSystem _zLevels;

    private readonly List<StationMapBeaconControl> _buttons = new();
    private readonly List<int> _knownFloors = new();
    private bool _updatingFloorSelector;
    private int _sourceFloor;
    private EntityUid? _sourceUid;
    private EntityUid? _trackedEntity;
    private int? _selectedFloor;

    public StationMapWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        _zLevels = _entMan.System<CESharedZLevelsSystem>();

        FilterBar.OnTextChanged += (bar) => OnFilterChanged(bar.Text);
        FloorSelector.OnItemSelected += OnFloorSelected;
    }

    public void Set(EntityUid sourceUid, string stationName, EntityUid? trackedEntity)
    {
        _sourceUid = sourceUid;
        _trackedEntity = trackedEntity;

        if (!string.IsNullOrEmpty(stationName))
        {
            StationName.Text = stationName;
        }

        RefreshFloorState();
    }

    private void OnFloorSelected(OptionButton.ItemSelectedEventArgs args)
    {
        args.Button.SelectId(args.Id);

        if (_updatingFloorSelector || args.Id < 0 || args.Id >= _knownFloors.Count)
            return;

        _selectedFloor = _knownFloors[args.Id];
        RefreshFloorState();
    }

    private void RefreshFloorState()
    {
        if (_sourceUid == null)
            return;

        var floorState = ZLevelFloorSelectorHelper.GetFloorState(
            _entMan,
            _zLevels,
            _sourceUid.Value,
            _selectedFloor);

        _selectedFloor = floorState.SelectedFloor;
        UpdateFloors(floorState.Floors, floorState.SelectedFloor, floorState.SourceFloor);
        SetMap(ZLevelFloorSelectorHelper.ResolveMapUid(_entMan, floorState.SelectedMap), _trackedEntity);
    }

    private void SetMap(EntityUid? mapUid, EntityUid? trackedEntity)
    {
        NavMapScreen.MapUid = mapUid;
        NavMapScreen.TrackedCoordinates.Clear();

        if (trackedEntity != null)
            NavMapScreen.TrackedCoordinates.Add(new EntityCoordinates(trackedEntity.Value, Vector2.Zero), (true, Color.Cyan));

        NavMapScreen.ForceNavMapUpdate();
        UpdateBeaconList(mapUid);
    }

    private void UpdateFloors(List<int> floors, int selectedFloor, int sourceFloor)
    {
        _sourceFloor = sourceFloor;
        _knownFloors.Clear();
        _knownFloors.AddRange(floors);

        _updatingFloorSelector = true;
        FloorSelector.Clear();

        for (var i = 0; i < floors.Count; i++)
        {
            FloorSelector.AddItem(ZLevelFloorSelectorHelper.FormatRelativeFloor(floors[i], _sourceFloor), i);
        }

        var selectedId = ZLevelFloorSelectorHelper.GetSelectedFloorIndex(floors, selectedFloor);
        FloorSelector.SelectId(selectedId);
        _updatingFloorSelector = false;

        FloorSelectorContainer.Visible = floors.Count > 1;
    }

    public void OnFilterChanged(string newFilter)
    {
        foreach (var button in _buttons)
        {
            button.Visible = string.IsNullOrEmpty(newFilter) || (
                !string.IsNullOrEmpty(button.Label) &&
                button.Label.Contains(newFilter, StringComparison.OrdinalIgnoreCase)
            );
        };
    }

    public void UpdateBeaconList(EntityUid? mapUid)
    {
        BeaconButtons.Children.Clear();
        _buttons.Clear();

        if (!mapUid.HasValue)
            return;

        if (!_entMan.TryGetComponent<NavMapComponent>(mapUid, out var navMap))
            return;

        foreach (var beacon in navMap.Beacons.Values)
        {
            var button = new StationMapBeaconControl(mapUid.Value, beacon);

            button.OnPressed += NavMapScreen.CenterToCoordinates;

            _buttons.Add(button);
        }

        _buttons.Sort();

        foreach (var button in _buttons)
            BeaconButtons.AddChild(button);
    }
}
