// SPDX-FileCopyrightText: 2023 chromiumboy <50505512+chromiumboy@users.noreply.github.com>
// SPDX-FileCopyrightText: 2024 Nemanja <98561806+EmoGarbage404@users.noreply.github.com>
// SPDX-FileCopyrightText: 2024 TGRCDev <tgrc@tgrc.dev>
// SPDX-FileCopyrightText: 2024 iacore <74560659+iacore@users.noreply.github.com>
// SPDX-FileCopyrightText: 2024 iacore <noreply+gpg-stub@1a-insec.net>
// SPDX-FileCopyrightText: 2024 metalgearsloth <31366439+metalgearsloth@users.noreply.github.com>
// SPDX-FileCopyrightText: 2025 Aiden <28298836+Aidenkrz@users.noreply.github.com>
//
// SPDX-License-Identifier: AGPL-3.0-or-later

using System.Numerics;
using Content.Client._Onyx.ZLevels.UI;
using Content.Client.UserInterface.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Map;
using Content.Shared.Pinpointer;

namespace Content.Client.Pinpointer.UI;

[GenerateTypedNameReferences]
public sealed partial class StationMapWindow : FancyWindow
{
    [Dependency] private readonly IEntityManager _entMan = default!;

    private readonly List<StationMapBeaconControl> _buttons = new();
    // <Onyx-Tweak>
    private readonly List<int> _knownFloors = new();

    private EntityUid? _owner;
    private EntityUid? _trackedEntity;
    private int? _selectedFloorDepth;
    private bool _updatingFloorSelector;
    // </Onyx-Tweak>

    public StationMapWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        FilterBar.OnTextChanged += (bar) => OnFilterChanged(bar.Text);
        FloorSelector.OnItemSelected += OnFloorSelected; // <Onyx-Tweak>
    }

    public void Set(string stationName, EntityUid owner, EntityUid? trackedEntity) // <Onyx-Tweak edited>
    {
        _owner = owner; // <Onyx-Tweak edited>
        _trackedEntity = trackedEntity; // <Onyx-Tweak edited>
        if (!string.IsNullOrEmpty(stationName))
            StationName.Text = stationName;

        RefreshForSelectedFloor(); // <Onyx-Tweak edited>
    }

    public void OnFilterChanged(string newFilter)
    {
        foreach (var button in _buttons)
        {
            button.Visible = string.IsNullOrEmpty(newFilter) || (
                !string.IsNullOrEmpty(button.Label) &&
                button.Label.Contains(newFilter, StringComparison.OrdinalIgnoreCase)
            );
        };
    }

    public void UpdateBeaconList(EntityUid? mapUid)
    {
        BeaconButtons.Children.Clear();
        _buttons.Clear();

        if (!mapUid.HasValue)
            return;

        if (!_entMan.TryGetComponent<NavMapComponent>(mapUid, out var navMap))
            return;

        foreach (var beacon in navMap.Beacons.Values)
        {
            var button = new StationMapBeaconControl(mapUid.Value, beacon);

            button.OnPressed += NavMapScreen.CenterToCoordinates;

            _buttons.Add(button);
        }

        _buttons.Sort();

        foreach (var button in _buttons)
            BeaconButtons.AddChild(button);
    }

    // <Onyx-Tweak>
    private void OnFloorSelected(OptionButton.ItemSelectedEventArgs args)
    {
        args.Button.SelectId(args.Id);

        if (_updatingFloorSelector || args.Id < 0 || args.Id >= _knownFloors.Count)
            return;

        _selectedFloorDepth = _knownFloors[args.Id];
        RefreshForSelectedFloor();
    }

    private void RefreshForSelectedFloor()
    {
        if (_owner == null)
            return;

        var floorState = ZLevelFloorSelectorHelper.GetFloorState(_entMan, _owner.Value, _selectedFloorDepth);
        _selectedFloorDepth = floorState.SelectedFloor;
        UpdateFloors(floorState.Floors, floorState.SelectedFloor, floorState.MonitorFloor);

        var navMapUid = ZLevelFloorSelectorHelper.ResolveNavMapUidForMap(_entMan, floorState.SelectedMap);
        NavMapScreen.MapUid = navMapUid;
        NavMapScreen.TrackedCoordinates.Clear();

        if (_trackedEntity != null &&
            ZLevelFloorSelectorHelper.TryGetEntityDepth(_entMan, _trackedEntity.Value, out var depth) &&
            depth == floorState.SelectedFloor)
        {
            NavMapScreen.TrackedCoordinates.Add(new EntityCoordinates(_trackedEntity.Value, Vector2.Zero), (true, Color.Cyan));
        }

        NavMapScreen.ForceNavMapUpdate();
        UpdateBeaconList(navMapUid);
    }

    private void UpdateFloors(List<int> floors, int selectedFloor, int monitorFloor)
    {
        _knownFloors.Clear();
        _knownFloors.AddRange(floors);

        _updatingFloorSelector = true;
        FloorSelector.Clear();

        for (var i = 0; i < floors.Count; i++)
        {
            FloorSelector.AddItem(ZLevelFloorSelectorHelper.FormatRelativeFloor(floors[i], monitorFloor), i);
        }

        var selectedId = 0;
        for (var i = 0; i < floors.Count; i++)
        {
            if (floors[i] != selectedFloor)
                continue;

            selectedId = i;
            break;
        }

        FloorSelector.SelectId(selectedId);
        _updatingFloorSelector = false;
        FloorSelectorContainer.Visible = floors.Count > 1;
    }
    // </Onyx-Tweak>
}